### ISSUE TITLE
AskPDF部分PDF文件解读失效问题

### ISSUE THREAD

**Issue by kongyan66** [MuiseDestiny/zotero-gpt#100]
基本配置：已配置好GPT秘钥 + zetero-gpt最新版本(0.2.2)
问题：部分pdf文件在pending时不完整，导致无法正确获取文章信息
![image](https://user-images.githubusercontent.com/68680103/232437282-188b9eb6-3597-46af-9ed3-109f99a6d994.png)
导致以下结果：
![image](https://user-images.githubusercontent.com/68680103/232437523-6c648706-fa92-4bea-8461-d6dafe37c624.png)
疑惑：是tag的脚本的问题吗，还是部分PDF不支持？我试了三篇PDF，就一篇好使。

**Comment by MuiseDestiny** [comment]
15/16说明15页后是参考文献，插件不会把参考文献也作为输入。因为参考文献很容易与问题高度相关，从而影响最终答案。

**Comment by kongyan66** [comment]
> 15/16说明15页后是参考文献，插件不会把参考文献也作为输入。因为参考文献很容易与问题高度相关，从而影响最终答案。

但是回答的内容并与本篇PDF无关系，这是怎么回事呢？

**Comment by MuiseDestiny** [comment]
> > 15/16说明15页后是参考文献，插件不会把参考文献也作为输入。因为参考文献很容易与问题高度相关，从而影响最终答案。
> 
> 但是回答的内容并与本篇PDF无关系，这是怎么回事呢？

输入问题，点askPDF。我猜你可能回车了。导致askpdf的输出被中断

**Comment by kongyan66** [comment]
输入问题，点击askPDF, 不回车的话没有回答内容呢
![image](https://user-images.githubusercontent.com/68680103/232445412-70f72fbd-17e0-4cbb-9ee7-04a3692c4da7.png)
我该如何正确操作？

**Comment by MuiseDestiny** [comment]
没有配置密钥吧
截图这里。
![image](https://user-images.githubusercontent.com/51939531/232446441-5d94f828-a236-4b68-8dcb-a2d29ecb416a.png)

**Comment by kongyan66** [comment]
配置过了，对答功能都正常的！

**Comment by kongyan66** [comment]
我一共测试了四篇PDF，只有下面这篇是正常的，即输入问题，点击askPDF，对话框自动给出回答：
![image](https://user-images.githubusercontent.com/68680103/232461765-fcae2f92-9761-4af0-9a20-473883584ca7.png)
其它三篇，对话框无任何输出，其中一篇PDF的[下载地址](https://openaccess.thecvf.com/content_ICCV_2017/papers/Lin_Focal_Loss_for_ICCV_2017_paper.pdf)，作者你可以试下。
![image](https://user-images.githubusercontent.com/68680103/232462160-cdc1e36d-1a01-4f3a-940a-4e862e6cae83.png)

**Comment by MuiseDestiny** [comment]
pdf读取我也会有时候失败，下个版本会优化

**Comment by kongyan66** [comment]
好的，期待更稳定的版本
