### ISSUE TITLE
只有0.20版本可以激活，后续都无法激活

### ISSUE THREAD

**Issue by DUdewey** [MuiseDestiny/zotero-gpt#101]
如题，强制重启也不行，重装也不行

**Comment by MuiseDestiny** [comment]
激活啥

**Comment by MuiseDestiny** [comment]
shift /吗  是有问号也有斜杠那个斜杠。

**Comment by DUdewey** [comment]
谢谢回复，搞定了，原来只是0.2.0自动弹出这个插件。另外最新版本的ask pdf好像还是无法使用，插件右侧黑屏，出现很多的英文

**Comment by MuiseDestiny** [comment]
英文是报错信息。

**Comment by DUdewey** [comment]
好像是网址+文章内容

**Comment by MuiseDestiny** [comment]
没有截图很抽象

**Comment by DUdewey** [comment]
你好，突然又可以用了

**Comment by DUdewey** [comment]
![image](https://user-images.githubusercontent.com/130991884/232487913-791791f2-d753-4c14-8332-1a0bf72489ae.png)

**Comment by MuiseDestiny** [comment]
马上修复

**Comment by DUdewey** [comment]
感谢作者大大用爱发电，辛苦了

**Comment by MuiseDestiny** [comment]
重新下载最新安装重启

**Comment by DUdewey** [comment]
没有问题了 非常感谢，大大提高了阅读的理解速度和效率
