### ISSUE TITLE
请问我这样设置的标签为啥回答出来的是标签代码的内容？

### ISSUE THREAD

**Issue by csf2022scut** [MuiseDestiny/zotero-gpt#103]
![1](https://user-images.githubusercontent.com/117445516/232498187-cafca40b-8726-41ca-8c4d-2c41469de4f5.JPG)
![image](https://user-images.githubusercontent.com/117445516/232498260-ac01d5be-1b9a-41f6-b6fc-a0afa1f5f4f1.png)
选中条目/条目信息的摘要/PDF的摘要都不行
求解答，谢谢！
如果大佬能做个视频介绍下使用方法就更好了！

**Comment by MuiseDestiny** [comment]
> 如果大佬能做个视频介绍下使用方法就更好了！

因为还在开发，所以介绍很快容易被淘汰。

你这个应该是内部代码有问题

![image](https://user-images.githubusercontent.com/51939531/232500152-88b1a839-ac66-48e6-a140-365ec06b17db.png)

长按`摘要提问`，进去把代码用截图这个包裹

**Comment by csf2022scut** [comment]
> > 如果大佬能做个视频介绍下使用方法就更好了！
> 
> 因为还在开发，所以介绍很快容易被淘汰。
> 
> 你这个应该是内部代码有问题
> 
> ![image](https://user-images.githubusercontent.com/51939531/232500152-88b1a839-ac66-48e6-a140-365ec06b17db.png)
> 
> 长按，进去把代码用截图这个包裹`摘要提问`

用了的，他获取不到摘要的内容。。。

**Comment by MuiseDestiny** [comment]
> > > 如果大佬能做个视频介绍下使用方法就更好了！
> > 
> > 
> > 因为还在开发，所以介绍很快容易被淘汰。
> > 你这个应该是内部代码有问题
> > ![image](https://user-images.githubusercontent.com/51939531/232500152-88b1a839-ac66-48e6-a140-365ec06b17db.png)
> > 长按，进去把代码用截图这个包裹`摘要提问`
> 
> 用了的，他获取不到摘要的内容。。。

截图看看。最好把里面内容发到这里。

**Comment by csf2022scut** [comment]
![image](https://user-images.githubusercontent.com/117445516/232515027-2af3968f-bc64-4587-ab01-2aee8930d5df.png)
#摘要提问[position=0][color=#5037E0]
下面是一篇论文的摘要：
'''js
const ztoolkit = Zotero.ZoteroGPT.data.ztoolkit
let getSelection = () => {
    return ztoolkit.Reader.getSelectedText(
 Zotero.Reader.getByTabID(Zotero_Tabs.selectedID)
    );
}
getSelection()
'''
请你依据这篇文章的摘要告诉我这篇文章讲了啥？

**Comment by MuiseDestiny** [comment]
是反引号，三个，一般位于键盘最左上角esc下面。属于markdown语法。你再改一下。不是英文单引号

**Comment by csf2022scut** [comment]
> 是反引号，三个，一般位于键盘最左上角esc下面。属于markdown语法。你再改一下。不是英文单引号

![image](https://user-images.githubusercontent.com/117445516/232520226-c266bf91-98fc-49ca-ae83-00012194fab7.png)
还是不行，只是不回答代码了，而且不知道是不是用的免费API的原因很容易卡在GPT is answering的位置

**Comment by MuiseDestiny** [comment]
下面是一篇文行的摘要:

```js
Meet.Zotero.getItemField("abstractNote")
```

![image](https://user-images.githubusercontent.com/51939531/232522232-6acface6-ff7f-4ee4-9f46-ad5f2d701e9b.png)


...

**Comment by csf2022scut** [comment]
> 下面是一篇文行的摘要:
> 
> ```js
> Meet.Zotero.getItemField("abstractNote")
> ```
> 
> ![image](https://user-images.githubusercontent.com/51939531/232522232-6acface6-ff7f-4ee4-9f46-ad5f2d701e9b.png)
> 
> ...

这个可以了，谢谢大佬！
