### ISSUE TITLE
为什么我的 zotero-gpt 界面还是老的 没有ask-pdf等标签

### ISSUE THREAD

**Issue by wangfh5** [MuiseDestiny/zotero-gpt#104]
![image](https://user-images.githubusercontent.com/51868839/232498596-0f05534c-564f-4ab5-92bd-f9fc26a329a1.png)
下载的是最新版
![image](https://user-images.githubusercontent.com/51868839/232498702-7c05164e-861e-4bfa-b13e-da84cf04e7a9.png)

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/232499604-72235dfe-fe24-4e42-b6a9-dec1b9e48b3e.png)

设置成 []

**Comment by wangfh5** [comment]
OK了 大佬回复真快
