### ISSUE TITLE
/model gpt-4 提示没有改插件

### ISSUE THREAD

**Issue by Hayesss** [MuiseDestiny/zotero-gpt#107]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

/model gpt-4 提示没有改插件  是需要设置的本人API下，购买GPT4嘛

**Comment by lrm2017** [comment]
> ### 这个问题是否已有issue
> * [x]  我确认没有已有issue，且已阅读**常见问题**
> 
> ### 运行环境
> * **OS**:
> * **Zotero version**:
> * **Plugin version**:
> 
> ### 当前配置信息
> _No response_
> 
> ### 问题详情
> /model gpt-4 提示没有改插件 是需要设置的本人API下，购买GPT4嘛
> 
> ### 补充说明
> _No response_

gpt-4 api 没那么好申请的，我购买了gpt4会员，申请了一个月都没拿到gpt4 api。不是你设置mode为gpt4就能使用的

**Comment by zfb132** [comment]
@Hayesss  请先阅读 [secretKey和api常见问题](https://github.com/MuiseDestiny/zotero-gpt/wiki/secretKey%E5%92%8Capi%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1-%E5%A6%82%E4%BD%95%E5%BE%97%E5%88%B0secretkey)
> 支持模型：`gpt-3.5-turbo`、`gpt-4`（需申请 [gpt-4-api](https://openai.com/waitlist/gpt-4-api)）

@lrm2017 我是用了10天收到审核通过的邮件，可能比较幸运吧

**Comment by lrm2017** [comment]
> 

兄弟，您是填的公司么，我是填学校，试了好几次没过。可以讲讲您是如何填写申请信息的么

**Comment by zfb132** [comment]
跟这个应该没关系，我是随便填的学校名字母

**Comment by Sober-J** [comment]
> @Hayesss 请先阅读 [secretKey和api常见问题](https://github.com/MuiseDestiny/zotero-gpt/wiki/secretKey%E5%92%8Capi%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#1-%E5%A6%82%E4%BD%95%E5%BE%97%E5%88%B0secretkey)
> 
> > 支持模型：`gpt-3.5-turbo`、`gpt-4`（需申请 [gpt-4-api](https://openai.com/waitlist/gpt-4-api)）
> 
> @lrm2017 我是用了10天收到审核通过的邮件，可能比较幸运吧

想问一下怎么申请GPT-4的API啊，买了GPT-4 Plus版的哪个API不是GPT-4的吗？
