### ISSUE TITLE
请问如何复制粘贴gpt生成的答案

### ISSUE THREAD

**Issue by ShushuFAN** [MuiseDestiny/zotero-gpt#111]
我看见昨天b站发布的演示视频（https://www.bilibili.com/video/BV1Hm4y127EL/?spm_id_from=333.999.0.0&vd_source=27c0d2b44888827407aa5ce7a5ec7f34）里40秒左右，是可以快速粘贴gpt的答案到note里的，但是我没搞明白是怎么做到的。是自定义快捷键或者命令吗？

**Comment by MuiseDestiny** [comment]
双击

**Comment by Invincible-Dhh** [comment]
> 双击

双击没反应呀。。。
