### ISSUE TITLE
invalid_request_error 各位大佬帮帮忙

### ISSUE THREAD

**Issue by xu384603970** [MuiseDestiny/zotero-gpt#113]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: windows 10
- **Zotero version**: 6.0.23
- **Plugin version**:  0.2.3

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...cDy7
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

当我鼠标点击askPDF,提示[''] is not valid under any of the given schemas-'input'
<img width="305" alt="zotero-gpt issue" src="https://user-images.githubusercontent.com/52403814/233587262-9807934d-9b39-4038-a42e-fd516f922fbf.PNG">
相关设置如下图所示：
<img width="305" alt="zotero-gpt issue" src="https://user-images.githubusercontent.com/52403814/233587395-906e42e8-3ec3-4164-91e8-3df0c8e7fe36.PNG">

**Comment by MuiseDestiny** [comment]
要输入问题后点击
