### ISSUE TITLE
AskPDF NULL invalid_reuqest_error

### ISSUE THREAD

**Issue by QQsunny** [MuiseDestiny/zotero-gpt#114]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS: windows 11**: 
- **Zotero version 6.0.26**: 
- **Plugin version 0.2.5**: 
![Screenshot (141)](https://user-images.githubusercontent.com/27815743/233714060-3aad8ee2-815c-4291-8eaf-e901822e086d.png)

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...R9rz
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

AskPDF 会出现[''] invalid_request_error
# null
> https://api.openai.com/v1/embeddings
**invalid_request_error**
[''] is not valid under any of the given schemas - 'input'

### 补充说明

试了不同大小的PDF 文件都有这个问题

**Comment by zfb132** [comment]
#113 试一下这个问题的答案

**Comment by talon0426** [comment]
一样，你同时使用了translate插件吗？
