### ISSUE TITLE
将对话框固定在右侧信息/笔记栏或许会更合适些

### ISSUE THREAD

**Issue by benlw** [MuiseDestiny/zotero-gpt#12]
首先感谢大佬的开源精神。

我试着编辑过几个标签，不知道它是如何处理tokes一下选中特别多的问题（prompt太多一般需要分批处理），以及如何处理不可选中文字的pdf？

有个不成熟的建议，感觉把对话框固定在右侧会更符合使用习惯。有时候浮动会导致跟随鼠标移动，对于不熟悉这款插件的人来说或许会有点不习惯吧。

**Comment by MuiseDestiny** [comment]
不固定，固定了就没有灵魂了。gpt知道它被锁住会伤心的

**Comment by MuiseDestiny** [comment]
按住窗口可以移动浮动窗。正常情况下不会跟随鼠标移动的。

**Comment by MuiseDestiny** [comment]
> 以及如何处理不可选中文字的pdf

这可能是ocr的问题了
