### ISSUE TITLE
回答无法进行复制，鼠标双击后无效，重启应用也没有解决

### ISSUE THREAD

**Issue by hyhshgk2** [MuiseDestiny/zotero-gpt#120]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

请问大佬，怎么能修复复制问题？同时，未来能否进行自选复制，而不是总体复制呢？

**Comment by Rubylyp** [comment]
我也遇到这个问题。zotero gpt中其他的功能觉得非常好用，问答也还算是流畅。只是回答的结果无法被复制，双击大多时候没有反应，这让人觉得问题经常白问了。求大佬出个自选复制的功能吧

**Comment by MuiseDestiny** [comment]
> 请问大佬，怎么能修复复制问题？同时，未来能否进行自选复制，而不是总体复制呢？

因为鼠标按住拖动，与选择复制操作冲突。所以没有加这个功能。正常都是可以双击复制的

**Comment by Rubylyp** [comment]
多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助

**Comment by cesium94** [comment]
> 多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助

仍未能解决此bug

**Comment by MuiseDestiny** [comment]
> > 多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助
> 
> 仍未能解决此bug

这不是bug，正常情况下，打开一个笔记。双击会插入文字到笔记。只是这个特性需要最新的better notes插件。

**Comment by kongyan66** [comment]
> > > 多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助
> > 
> > 
> > 仍未能解决此bug
> 
> 这不是bug，正常情况下，打开一个笔记。双击会插入文字到笔记。只是这个特性需要最新的better notes插件。

better notes 已经是最新版本：0.8.9, 但在PDF阅读界面，回答框内容，确实无法双击复制，双击无任何反应，怎么解决呢？之前0.2.4版本是正常的呢。

**Comment by MuiseDestiny** [comment]
> > > > 多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助
> > > 
> > > 
> > > 仍未能解决此bug
> > 
> > 
> > 这不是bug，正常情况下，打开一个笔记。双击会插入文字到笔记。只是这个特性需要最新的better notes插件。
> 
> 在PDF阅读界面，回答框内容，确实无法双击复制，双击无任何反应，怎么解决呢？之前0.2.4版本是正常的呢。


先用0.2.4，或者等更新修复

**Comment by kongyan66** [comment]
> > > > > 多谢大佬的解答，我刚发现是一个冲突：在右侧打开条目笔记时，即使光标未放置到笔记中，双击是无法复制回答的内容的；将pdf右侧的条目笔记关闭或移动到独立窗口时，双击gpt回答即可正常复制。再次感谢大佬的帮助
> > > > 
> > > > 
> > > > 仍未能解决此bug
> > > 
> > > 
> > > 这不是bug，正常情况下，打开一个笔记。双击会插入文字到笔记。只是这个特性需要最新的better notes插件。
> > 
> > 
> > 在PDF阅读界面，回答框内容，确实无法双击复制，双击无任何反应，怎么解决呢？之前0.2.4版本是正常的呢。
> 
> 先用0.2.4，或者等更新修复

好的呢
