### ISSUE TITLE
s

### ISSUE THREAD

**Issue by GGCMT1** [MuiseDestiny/zotero-gpt#122]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**: windows11
- **Zotero version**: 6.0.23
- **Plugin version**: 
0.2.5

### Issue Details

点击ASKPDF，显示your secretkey isnot configured

**Comment by MuiseDestiny** [comment]
请重新编辑后重开

**Comment by MuiseDestiny** [comment]
your secretkey isnot configured

翻译后是，你的密钥未配置。
