### ISSUE TITLE
如何自定义tag问题

### ISSUE THREAD

**Issue by Bring633** [MuiseDestiny/zotero-gpt#123]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Mac OS
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.5

### 问题详情

如果我需要写一个tag，这个tag问的是固定的问题。需要在怎么调用代码？

比如，我基于AskPDF tag来二次开发， 新的tag 用于解决“ 这篇文章用到了什么技术”。我需要怎么修改AskPDF tag呢？

我尝试过将AskPDF tag中的js代码直接换成 问题文本 但是返回的信息报错。

### 补充说明

稳定复现

**Comment by MuiseDestiny** [comment]
1. 长按askpdf，把#askpdf改名
2. 把最后的gptinutString那里，换成你的具体问题
3. Ctrl S保存

**Comment by wwzlin** [comment]
抱歉，没有明白第2步如何操作

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/234505842-701e6a97-2e4f-462f-be63-91d97fbcc8e5.png)

选中部分替换成你的问题。${}内部是代码块。

**Comment by wwzlin** [comment]
感谢，我来试一下。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Polygon ***@***.***>
发送时间: Wednesday, April 26, 2023 3:46:51 PM
收件人: MuiseDestiny/zotero-gpt ***@***.***>
抄送: wwzlin ***@***.***>; Comment ***@***.***>
主题: Re: [MuiseDestiny/zotero-gpt] 如何自定义tag问题 (Issue #123)


[image]<https://user-images.githubusercontent.com/51939531/234505842-701e6a97-2e4f-462f-be63-91d97fbcc8e5.png>

选中部分替换成你的问题。${}内部是代码块。

―

**Comment by Bring633** [comment]
> ![image](https://user-images.githubusercontent.com/51939531/234505842-701e6a97-2e4f-462f-be63-91d97fbcc8e5.png)
> 
> 选中部分替换成你的问题。${}内部是代码块。

我尝试过这样修改tag
<img width="302" alt="Screen Shot 2023-04-26 at 15 52 21" src="https://user-images.githubusercontent.com/89834755/234507796-50dab6df-97f6-4232-9ffe-d6432b158731.png">

但是openai会这样报错

<img width="397" alt="Screen Shot 2023-04-26 at 15 54 39" src="https://user-images.githubusercontent.com/89834755/234508096-4e5e3140-3928-4927-98a7-1256423232a4.png">

**Comment by MuiseDestiny** [comment]
#🪐AskPDF[position=10][color=#0EA293][trigger=/^(本文|这篇文章|论文)/]
You are a helpful assistant. Context information is below.
${
Meet.Global.views.messages = [];
Meet.Global.input = "你的问题"
Meet.Zotero.getRelatedText(Meet.Global.input)
}
Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information.

Answer the question: ${Meet.Global.input}

Reply in zh-CN

**Comment by MuiseDestiny** [comment]
复制我发的粘贴进去，把`你的问题`改成你的问题

注意不要把引号删除了

**Comment by MuiseDestiny** [comment]
需要有一点代码基础。不然不好改的。这里input用到两次，一次是参与向量计算，找到相关段落。一次是最后问gpt时候。

**Comment by Bring633** [comment]
> 需要有一点代码基础。不然不好改的。这里input用到两次，一次是参与向量计算，找到相关段落。一次是最后问gpt时候。

感谢大佬，后面可以补充一下各个接口的使用方式。我去读源代码了XD

**Comment by kongyan66** [comment]
作者你好，想问下tag的代码块每次更新版本都有所变化，请问下是否向前兼容，老版本的tag在新版本中都能正常用吗？（我试了一部分是通用的，但不知道性能是否有区别），不同版本同一功能代码块(比如都是获取选中内容的）是否有区别呢？

**Comment by MuiseDestiny** [comment]
> 作者你好，想问下tag的代码块每次更新版本都有所变化，请问下是否向前兼容，老版本的tag在新版本中都能正常用吗？（我试了一部分是通用的，但不知道性能是否有区别），不同版本同一功能代码块(比如都是获取选中内容的）是否有区

用[Meet的API](https://github.com/MuiseDestiny/zotero-gpt/blob/bootstrap/src/modules/Meet/api.ts)可以的，文字部分可以照抄，代码部分用Meet的。内置的都是属于示例，比较基础的，通用的，鼓励自己根据自己研究领域定制标签。

**Comment by ziyuanzhao2000** [comment]
请问怎么删除新增的 tag 呢？ ctrl-S 貌似会存成新的

**Comment by MuiseDestiny** [comment]
> 请问怎么删除新增的 tag 呢？ ctrl-S 貌似会存成新的

右键长按一下
