### ISSUE TITLE
和zotero gpt 相关的操作全部Request timed out

### ISSUE THREAD

**Issue by leoatchina** [MuiseDestiny/zotero-gpt#127]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Win10 21H2 ， 在台机和笔记本上都出现
- **Zotero version**:  6.0.26
- **Plugin version**:  0.25

### 问题详情

和zotero gpt 相关的操作全部这样, request timed out
![image](https://user-images.githubusercontent.com/4470821/235070021-10c7e6cc-bcf0-4569-8fd3-f520b7152c44.png)

**是不是api也要设置？**

1. api key我生成了， 确定没复制错， 是美国的朋友充值注册的
![image](https://user-images.githubusercontent.com/4470821/235069607-c7857dac-9438-47a8-885f-a14b82d19731.png)
2. 上述的secret key我在本插件里用过， 后面生成的zotero key也用过，都不行，一样的问题。
3.  zotero key显示`never uesd`， 说明没有访问不 
4.  secret key 我可用于 微信机器人， 所以这个openapi账号没问题
![image](https://user-images.githubusercontent.com/4470821/235069976-746e255c-1dc6-4048-83a4-4383f45efb15.png)
5. 尝试在  zotero里设置   proxy.http,  proxy.socks, 在梯子没问题（v2rayn）的情况下，还是一样

### 补充说明

稳定复现，没有成功使用过这个插件

**Comment by leoatchina** [comment]
> /report回车截图
已经加上
![image](https://user-images.githubusercontent.com/4470821/235127107-c490d8f0-dcb3-40d8-8d58-04a0f7b65425.png)

**Comment by stone2211** [comment]
我的也是这种情况，请问解决了吗

**Comment by Mercy1101** [comment]
我也是同样的情况，第一次使用即一直 Request Time out，请问有解决么？

**Comment by MuiseDestiny** [comment]
> 我也是同样的情况，第一次使用即一直 Request Time out，请问有解决么？

用你能访问github的网络环境给gpt，全局代理

**Comment by leoatchina** [comment]
> 

zotero里可以设置全局代理 ，不过能兄弟你能单独给zotero gpt设置代理参数不？

**Comment by MuiseDestiny** [comment]
> 

抱歉，我不是很懂这方面

**Comment by verve91** [comment]
这个用api的不分ip，只要不在国内就行，所以你这个问题，应该不是网络问题，我的就是有很多线网页进不去，但是不影响zotero gpt 使用。

**Comment by tsengkimhung** [comment]
我也是同样的情况，第一次使用即一直 Request Time out，请问有解决么？

**Comment by leoatchina** [comment]
> 我也是同样的情况，第一次使用即一直 Request Time out，请问有解决么？

设置电脑全局翻墙

**Comment by leoatchina** [comment]
最好是在这个插件里能设置代理

**Comment by Yu000910** [comment]
> ### 这个问题是否已有issue
> * [x]  我确认没有已有issue，且已阅读**常见问题**
> 
> ### 运行环境
> * **OS**:  Win10 21H2 ， 在台机和笔记本上都出现
> * **Zotero version**:  6.0.26
> * **Plugin version**:  0.25
> 
> ### 当前配置信息
> _No response_
> 
> ### 问题详情
> 和zotero gpt 相关的操作全部这样, request timed out ![image](https://user-images.githubusercontent.com/4470821/235070021-10c7e6cc-bcf0-4569-8fd3-f520b7152c44.png)
> 
> **是不是api也要设置？**
> 
> 1. api key我生成了， 确定没复制错， 是美国的朋友充值注册的
>    ![image](https://user-images.githubusercontent.com/4470821/235069607-c7857dac-9438-47a8-885f-a14b82d19731.png)
> 2. 上述的secret key我在本插件里用过， 后面生成的zotero key也用过，都不行，一样的问题。
> 3. zotero key显示`never uesd`， 说明没有访问不
> 4. secret key 我可用于 微信机器人， 所以这个openapi账号没问题
>    ![image](https://user-images.githubusercontent.com/4470821/235069976-746e255c-1dc6-4048-83a4-4383f45efb15.png)
> 5. 尝试在  zotero里设置   proxy.http,  proxy.socks, 在梯子没问题（v2rayn）的情况下，还是一样
> 
> ### 补充说明
> 稳定复现，没有成功使用过这个插件

在输入框中输入:
/api https://api.openai-proxy.com 就可以了

**Comment by hanna184084** [comment]
域名改了后显示这个怎么办
![Uploading 截屏2024-01-17 16.41.33.png…]()

**Comment by Yu000910** [comment]
看不到上传的png。

**Comment by nepwell** [comment]
> > 我也是同样的情况，第一次使用即一直 Request Time out，请问有解决么？
> 
> 用你能访问github的网络环境给gpt，全局代理

我用的是全局代理然后在这个网络下我能够访问网页的gpt但是在zotero这个插件上还是超时，版本是zotero7

**Comment by wwsdad** [comment]
> > 
> 
> 抱歉，我不是很懂这方面



> 最好是在这个插件里能设置代理

如何在插件设置全局代理？
