### ISSUE TITLE
建议增加API地址设定

### ISSUE THREAD

**Issue by ChenzihaoWork** [MuiseDestiny/zotero-gpt#13]
很多GPT的项目都可以自定义API地址，比如CHATGPT-WEB，问天等等的。解决的是在不能科学上网的情况下也能使用gpt的服务，api的地址可以反代或者cf worker的。
所以我也建议可以自定义自己的api地址

**Comment by ifeitao** [comment]
确实，不使用反代很容易被封的。

**Comment by zfb132** [comment]
最新版已经支持，示例  
`/api https://api.openai.com/v1`
