### ISSUE TITLE
非问题反馈：如何像视频中一样直接将复制的md/html内容解析进笔记

### ISSUE THREAD

**Issue by systemoutprintlnhelloworld** [MuiseDestiny/zotero-gpt#133]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: win11 preview
- **Zotero version**:  6.026
- **Plugin version**: 0.26

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...6807
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

您发的视频中[该片段](https://www.bilibili.com/video/BV1Hm4y127EL?t=188.8)显示您双击把gpt生成的html自动复制到better notes的条目笔记中，此处我有两个疑问：
1. BN的`0.89`和beta版`1.07`我都试过了，但是仍然未成功实现双击gpt面板自动复制到BN内
2. BN`0.89`版本以下两个功能能实现粘贴为对应格式，但是未能如作者视频显示直接进行解析
![image](https://user-images.githubusercontent.com/62531937/235673152-585ef7d5-40c3-4c13-ae02-72dfc93ceeb2.png)

**Comment by MuiseDestiny** [comment]
1.打开笔记或处于Better Notes主笔记内
2.双击回答区域，此时默认会复制内容，如果满足1，会把输出内容插入*到笔记。

*注意，这种插入是html的插入，与用户直接粘贴不等价。所以才实现了插入到笔记的功能。
