### ISSUE TITLE
【Width】宽度设置可以使用鼠标拖动吗

### ISSUE THREAD

**Issue by songyuc** [MuiseDestiny/zotero-gpt#135]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 22H2
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

您好！宽度设置可以使用鼠标拖动来修改吗

**Comment by MuiseDestiny** [comment]
可以，但是写UI太麻烦了，容易有新的bug，不想写，欢迎PR。
