### ISSUE TITLE
显示Null 无法正确使用

### ISSUE THREAD

**Issue by tianziyikeke** [MuiseDestiny/zotero-gpt#136]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: windows10 21H2
- **Zotero version**:6.0.26 
- **Plugin version**: 0.2.6

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...WF68
`model` gpt-3.5-turbo
`temperature` 0.5

### 问题详情

![image](https://user-images.githubusercontent.com/38697723/236135629-15476930-9347-4f89-a8ac-2afb196cbde4.png)
下面的每个选项都不能正确使用，配置正确，不知道哪里有问题

### 补充说明

一直不能正确使用插件，请问是什么问题？

**Comment by MuiseDestiny** [comment]
密钥过期，或无费用。与插件无关。

**Comment by tianziyikeke** [comment]
谢谢！
