### ISSUE TITLE
URI存在错误

### ISSUE THREAD

**Issue by Ellenscode719** [MuiseDestiny/zotero-gpt#137]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

OS: Windows11 22H2
Zotero version: 6.0.23
Plugin version: 0.2.3

### 当前配置信息

`api` sk-LTzNWhTRCo78r5iJak2F.......
`secretKey` sk-...RvhU
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

![image](https://user-images.githubusercontent.com/129271350/236190034-93312419-c1d6-4ffa-98bb-8950e42b984c.png)

**Comment by Ellenscode719** [comment]
解决了，是API没设置好

**Comment by geoere** [comment]
怎么解决的大佬 我最近遇到这种问题

**Comment by Ellenscode719** [comment]
> 

API Key换新的能用的就可以了
