### ISSUE TITLE
关闭问题

### ISSUE THREAD

**Issue by Yangning-k** [MuiseDestiny/zotero-gpt#138]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

当我不再使用时，请问应如何关闭该插件？

**Comment by MuiseDestiny** [comment]
ESC。可以输入/help看下基本使用方法

**Comment by kongyan66** [comment]
虽然可以esc关闭文本框，有的时候触发不了，能不能设计一个一键关闭GPT提问页面的内容呢，一点小小建议哈

**Comment by MuiseDestiny** [comment]
> 虽然可以esc关闭文本框，有的时候触发不了，能不能设计一个一键关闭GPT提问页面的内容呢，一点小小建议哈

gpt的输入框激活状态下按esc

**Comment by Yangning-k** [comment]
好的，谢谢

**Comment by Yangning-k** [comment]
> ESC。可以输入/help看下基本使用方法

好的，谢谢

**Comment by LincanXu** [comment]
在mac os使用的时候，全屏zotero情况下esc会优先退出全屏，然后才是退出gpt插件，这种有什么好的方案避免吗
