### ISSUE TITLE
点击askpdf之后询问问题显示不出回答

### ISSUE THREAD

**Issue by ChrisChen0929** [MuiseDestiny/zotero-gpt#139]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**:  

### 当前配置信息

`api` https://openai.api2d.net/v1
`secretKey` fk1...x91K
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

右下角显示

**Comment by ChrisChen0929** [comment]
![image](https://user-images.githubusercontent.com/105934462/236483316-53abe85c-f585-4239-b0ed-6c89adeefe3d.png)

**Comment by MuiseDestiny** [comment]
api那里v1去掉试试

**Comment by ChrisChen0929** [comment]
> api那里v1去掉试试

还是不行，输入问题按回车之后运行的是”item“这个tag，但这个tag鼠标右键长按删不掉

**Comment by MuiseDestiny** [comment]
> > api那里v1去掉试试
> 
> 还是不行，输入问题按回车之后运行的是”item“这个tag，但这个tag鼠标右键长按删不掉

点击askpdf

**Comment by ChrisChen0929** [comment]
> > > api那里v1去掉试试
> > 
> > 
> > 还是不行，输入问题按回车之后运行的是”item“这个tag，但这个tag鼠标右键长按删不掉
> 
> 点击askpdf

点击askpdf没反应，会不会是tag内代码的问题呢，幸苦您看一下，谢谢！

#🪐AskPDF[position=0][color=#009FBD][trigger=]

You are a helpful assistant. Context information is below.

---
```js
window.gptInputString = Zotero.ZoteroGPT.views.inputContainer.querySelector("input").value
Zotero.ZoteroGPT.views.messages = [];

Zotero.ZoteroGPT.utils.getRelatedText(
"127.0.0.1:5000", window.gptInputString 
)

```
---

Current date: ```js
String(new Date())
```
Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information. 

Answer the question:
```js
window.gptInputString 
```

Reply in 简体中文

**Comment by ChrisChen0929** [comment]
![image](https://user-images.githubusercontent.com/105934462/236498833-afaa0c18-9aec-4a9f-a221-c8a83188f055.png)
现在只回我一个问号了哈哈哈

**Comment by MuiseDestiny** [comment]
内部代码太老了，插件改更新了

**Comment by ChrisChen0929** [comment]
> 内部代码太老了，插件改更新了

请问最新版本是0.2.6吗

**Comment by ChrisChen0929** [comment]
换了一篇论文又可以用askpdf了，谢谢作者的答复
