### ISSUE TITLE
GPT输出代码片段，无法执行

### ISSUE THREAD

**Issue by panwanke** [MuiseDestiny/zotero-gpt#14]
尝试使用 gpt 输出的代码添加文献标签。结果发现，gpt 只会输出代码文本，而不会执行它。

我尝试修改 prompt，让 gpt 用 ```js``` 包裹输出的代码。gpt 的输出结果也还是文本，无法运行。

**Comment by MuiseDestiny** [comment]
#添加摘要标签[c=#7149C6][pos=1]
现在请你从下面的摘要中分析出三个标签：
```js
i = ZoteroPane.getSelectedItems()[0];
i.getField("abstractNote");
```
然后给我一段代码用于向Zotero选中条目添加你分析出的标签，示例代码如下，你只需要输出代码：

i = ZoteroPane.getSelectedItems()[0];
tags = ["tag1", "tag2"];
tags.forEach(tag=>i.addTag(tag));
await i.saveTx();
你给出的代码为：





---

上面是我的，供参考

**Comment by MuiseDestiny** [comment]
> 你给出的代码为：

这句很关键的

**Comment by MuiseDestiny** [comment]
不写，可能输出不是纯代码，有一些他对你提问的概括。

**Comment by panwanke** [comment]
> 


> 这句很关键的
> 不写，可能输出不是纯代码，有一些他对你提问的概括。

感谢，确实是这样。   是我改代码的时候忽略了。

**Comment by JeffeyChou** [comment]
跟[Asynchro-Epool](https://github.com/Asynchro-Epool)遇到一样的问题，使用了作者改进后的prompt后就可以执行了。复现后发现关键确实是“你只需要输出代码：”，“你给出的代码为：”，需要确保返回的只有纯代码
