### ISSUE TITLE
Token数量问题

### ISSUE THREAD

**Issue by Ricardo-F-X** [MuiseDestiny/zotero-gpt#140]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: MacOS 13.4 Beta版(22F5059b)
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.6

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...Ixb3
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

每次在进行ask pdf 以及 translate 的过程中，一直提示token不足。
但是同样的prompt偶尔可以过，偶尔会卡tokens。复现率大概80%
<img width="1667" alt="截屏2023-05-06 09 52 30" src="https://user-images.githubusercontent.com/20970356/236592163-339e78f9-aedd-49dd-9b49-f710171d4283.png">

### 补充说明

基本稳定复现，复现率80%
与pdf无关

**Comment by Ricardo-F-X** [comment]
<img width="1112" alt="截屏2023-05-06 09 59 03" src="https://user-images.githubusercontent.com/20970356/236592250-b517237a-2bfc-4669-afd8-4f302b790bb7.png">

**Comment by Ricardo-F-X** [comment]
<img width="1000" alt="截屏2023-05-06 10 00 28" src="https://user-images.githubusercontent.com/20970356/236592564-71146799-db13-4d56-b19a-acc7a41baa21.png">

**Comment by MuiseDestiny** [comment]
/clear  回车清空历史消息

同时chatNumber设置小一点

**Comment by Ricardo-F-X** [comment]
感谢！BTW，chatNum和relatedNum是什么意义？

**Comment by MuiseDestiny** [comment]
> 感谢！BTW，chatNum和relatedNum是什么意义？

chatNum是保留的历史对话数量。如果你上次问答文字太多，下次问答肯定会提示token不足。

relatedNum是从pdf搜索相关段落数量（涉及askpdf原理），要尽可能大，但不能太大（太大token不足）。
