### ISSUE TITLE
How to stop generation, are there any shortcuts?

### ISSUE THREAD

**Issue by LumaFilter** [MuiseDestiny/zotero-gpt#145]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### Issue Details

Are there any shortcut keys that can stop generating like the official website？

**Comment by Bailey-24** [comment]
点击 输入框，按esc

**Comment by MuiseDestiny** [comment]
ESC，或者直接输入一个新的问题回车。好像无法真正中断，只是界面上不显示了，token还是会消耗掉。
