### ISSUE TITLE
窗口拖动需求

### ISSUE THREAD

**Issue by remember00000** [MuiseDestiny/zotero-gpt#147]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

窗口能设置成可拖动的吗，以及交互式选中的话必须每次都点击selection吗

**Comment by MuiseDestiny** [comment]
本身就是可拖动的。不必每次点selection

**Comment by MuiseDestiny** [comment]
当你选中pdf文字，他会默认成为gpt对话的前文

**Comment by remember00000** [comment]
那对话窗口是可以拖动的吗

**Comment by MuiseDestiny** [comment]
> 那对话窗口是可以拖动的吗

可以

**Comment by remember00000** [comment]
好的，这里历史对话信息可以保留现实吗

**Comment by MuiseDestiny** [comment]
> 好的，这里历史对话信息可以保留现实吗

啥

**Comment by remember00000** [comment]
针对一个问题进行的多轮对话信息的历史问答是可以显示的吗，还是说这里只能是单轮对话，所以不保留历史对话信息呢，谢谢大佬快速恢复

**Comment by MuiseDestiny** [comment]
> 针对一个问题进行的多轮对话信息的历史问答是可以显示的吗，还是说这里只能是单轮对话，所以不保留历史对话信息呢，谢谢大佬快速恢复

/chatNumber可以设置你允许保留的最大历史对话数量。

它支持连续对话。但对于历史对话的显示还没开发。

**Comment by remember00000** [comment]
好的，另外窗口大小缩放好像也还不能调整

**Comment by MuiseDestiny** [comment]
> 好的，另外窗口大小缩放好像也还不能调整

/width ctrl 加鼠标滚轮。

完整体验后可以再提issue请求新功能

**Comment by remember00000** [comment]
好的，感谢
