### ISSUE TITLE
持久化 embedding 生成结果

### ISSUE THREAD

**Issue by 18870** [MuiseDestiny/zotero-gpt#149]
使用 askPDF 功能会调用 embedding 接口生成向量，但是重启 zotero 后相同的文章需要重新生成。
可以接入向量数据库或者存储在 zotero 条目内，不知道是否能实现。

**Comment by MuiseDestiny** [comment]
>  askPDF 功能会调用 embedding 接口生成向量

本身就是储存本地的，初次会Generating，以后会reading embedding

**Comment by 18870** [comment]
对，
> 但是重启 zotero 后相同的文章需要重新生成。

还是我看错了

**Comment by MuiseDestiny** [comment]
> 对，
> 
> > 但是重启 zotero 后相同的文章需要重新生成。
> 
> 还是我看错了

只是重新读取文本哦，向量会读取缓存的。只要读取结果是一致的。设计最初就考虑储存了，不然太费钱了。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-gpt/blob/bootstrap/src/modules/Meet/OpenAI.ts#L55

感兴趣可以看这里逻辑。

只要md5结果一样会读取本地。

1. 为啥验证md5？
解析函数可能会优化，需要重新获取。
2. 为啥每次重新读取文本？
因为pdf全文储存太占本地空间，用计算机性能换储存。
