### ISSUE TITLE
复制问题，在文献外，点击标题的回答，可以划词复制，但是在文献内部，划选不能ctrl+c复制

### ISSUE THREAD

**Issue by verve91** [MuiseDestiny/zotero-gpt#151]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 
Zotero version: 6.0.23

### 当前配置信息

`api` https://api.chatanywhere.com.cn
`secretKey` sk-...ka2a
`model` gpt-3.5-turbo
`temperature` 0.1

### 问题详情

在文献外，点击标题的回答，可以划词复制，但是在文献内部，划选不能ctrl+c复制

**Comment by MuiseDestiny** [comment]
注意输入框是否获得焦点。
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/d1cc3c70-f13d-4a20-bfc2-f908faf5be8d)

**Comment by verve91** [comment]
确实可以，好了，感谢大佬
