### ISSUE TITLE
context_length_exceeded 报错

### ISSUE THREAD

**Issue by DQTC** [MuiseDestiny/zotero-gpt#154]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/119269401/3bf4c6e2-54f6-4115-a5b4-5e66e0bcba1a)
# 
> https://api.openai.com/v1/chat/completions

**invalid_request_error**
This model's maximum context length is 4097 tokens. However, your messages resulted in 4184 tokens. Please reduce the length of the messages.

请问以上问题如何解决？

**Comment by DQTC** [comment]
> /clear 回车

您好，我试过了，但是没有，是之后还要重启一下吗

**Comment by MuiseDestiny** [comment]
> > /clear 回车
> 
> 您好，我试过了，但是没有，是之后还要重启一下吗

/relatedNumber设置小点

**Comment by DQTC** [comment]
> > > /clear 回车
> > 
> > 
> > 您好，我试过了，但是没有，是之后还要重启一下吗
> 
> /relatedNumber设置小点

设置成多少合适呢，我设置成了5.还是不行
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/119269401/64925967-c1f0-463d-a0dd-f36334a30e5a)

**Comment by MuiseDestiny** [comment]
> > > > /clear 回车
> > > 
> > > 
> > > 您好，我试过了，但是没有，是之后还要重启一下吗
> > 
> > 
> > /relatedNumber设置小点
> 
> 设置成多少合适呢，我设置成了5.还是不行 ![image](https://user-images.githubusercontent.com/119269401/239225425-64925967-c1f0-463d-a0dd-f36334a30e5a.png)

5是默认的 试试 3-2-1

**Comment by DQTC** [comment]
> > > > > /clear 回车
> > > > 
> > > > 
> > > > 您好，我试过了，但是没有，是之后还要重启一下吗
> > > 
> > > 
> > > /relatedNumber设置小点
> > 
> > 
> > 设置成多少合适呢，我设置成了5.还是不行 ![image](https://user-images.githubusercontent.com/119269401/239225425-64925967-c1f0-463d-a0dd-f36334a30e5a.png)
> 
> 5是默认的 试试 3-2-1

设置成2是可以的，但是效果的没有之前的好，有没有可以根治的办法？实在是麻烦您了

**Comment by MuiseDestiny** [comment]
> > > > > > /clear 回车
> > > > > 
> > > > > 
> > > > > 您好，我试过了，但是没有，是之后还要重启一下吗
> > > > 
> > > > 
> > > > /relatedNumber设置小点
> > > 
> > > 
> > > 设置成多少合适呢，我设置成了5.还是不行 ![image](https://user-images.githubusercontent.com/119269401/239225425-64925967-c1f0-463d-a0dd-f36334a30e5a.png)
> > 
> > 
> > 5是默认的 试试 3-2-1
> 
> 设置成2是可以的，但是效果的没有之前的好，有没有可以根治的办法？实在是麻烦您了

换pdf 5就可能可以了

**Comment by DQTC** [comment]
> > > > > > > /clear 回车
> > > > > > 
> > > > > > 
> > > > > > 您好，我试过了，但是没有，是之后还要重启一下吗
> > > > > 
> > > > > 
> > > > > /relatedNumber设置小点
> > > > 
> > > > 
> > > > 设置成多少合适呢，我设置成了5.还是不行 ![image](https://user-images.githubusercontent.com/119269401/239225425-64925967-c1f0-463d-a0dd-f36334a30e5a.png)
> > > 
> > > 
> > > 5是默认的 试试 3-2-1
> > 
> > 
> > 设置成2是可以的，但是效果的没有之前的好，有没有可以根治的办法？实在是麻烦您了
> 
> 换pdf 5就可能可以了

明白了，有可能是这篇文献的原因，对咩

**Comment by MuiseDestiny** [comment]
对的，这一篇段落有点长
