### ISSUE TITLE
密匙的填写格式？

### ISSUE THREAD

**Issue by Lieakks** [MuiseDestiny/zotero-gpt#16]
感谢用爱发电的大佬，请问密匙的填写格式是怎么样的呀？

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/228722416-cdbc44e3-a1af-48b0-8f6e-9fbc809fca1a.png)

**Comment by Lieakks** [comment]
感谢大佬，我明白了，我需要登录chatgpt去生成一个密匙。
