### ISSUE TITLE
windows 10 快捷按钮 图标异常

### ISSUE THREAD

**Issue by Geo123abc** [MuiseDestiny/zotero-gpt#161]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: windows 10 64bits
- **Zotero version**: v6.0.26
- **Plugin version**: v0.2.9

### 问题详情

和之前 zotero style 一样，图标大小异常，详见图片

![](https://s3.bmp.ovh/imgs/2023/05/22/003e513a7d37ab4d.png)

**Comment by MuiseDestiny** [comment]
首选项搜zoterogpt.buttons把它关了，这个按钮给键盘上没有快捷键的用户用的
