### ISSUE TITLE
能否支持基于网页封装的项目进行解析

### ISSUE THREAD

**Issue by kettly1260** [MuiseDestiny/zotero-gpt#164]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  WIN10 22H2
- **Zotero version**: 6.0.23
- **Plugin version**:  0.2.9

### 问题详情

目前基于api的收费标准较为昂贵，新注册的账号没有赠送的额度，找到了一个基于封装 OpenAI 网页版最新 ChatGPT 接口, 不需要使用 API Key, 应该可以代替api的使用。这是项目地址https://github.com/zhuweiyou/chatgpt-api

**Comment by MuiseDestiny** [comment]
插件不配置密钥情况下，就是调用的一个网站的api。但只能对话，很多功能用不了，比如askpdf，他需要构建向量。
