### ISSUE TITLE
插件自编译出错，报错信息如下，有东西找不到

### ISSUE THREAD

**Issue by stonegr** [MuiseDestiny/zotero-gpt#165]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

![截图_20230524104504](https://github.com/MuiseDestiny/zotero-gpt/assets/74632994/02413da4-07a2-44ce-83b8-f674d2e239c1)

**Comment by MuiseDestiny** [comment]
注释掉相关语句即可

**Comment by stonegr** [comment]
> 注释掉相关语句即可

你好，只需注释这两行吗？
![截图_20230524130912](https://github.com/MuiseDestiny/zotero-gpt/assets/74632994/0c24901b-442c-43ce-a7d1-12a3df7a5925)

**Comment by homeofmny** [comment]
> > 注释掉相关语句即可
> 
> 你好，只需注释这两行吗？ ![截图_20230524130912](https://user-images.githubusercontent.com/74632994/240492858-0c24901b-442c-43ce-a7d1-12a3df7a5925.png)

@stonegr 你好，请问一下你编译成功了吗？我把这两行注释掉后虽然编译成功，但是无法在Zotero运行，错误日志中显示WeakRef is not defined，想问一下你编译后的插件是正常的吗？
