### ISSUE TITLE
窗口不能自由移动，挡在屏幕中间影响看pdf

### ISSUE THREAD

**Issue by improve100** [MuiseDestiny/zotero-gpt#166]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  ubuntu
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

chatgpt窗口不能自由移动，挡在屏幕中间影响看pdf

**Comment by MuiseDestiny** [comment]
ctrl ➕ 鼠标拖拽
