### ISSUE TITLE
设置字体大小

### ISSUE THREAD

**Issue by zichunxx** [MuiseDestiny/zotero-gpt#167]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows 10
- **Zotero version**:  6.0.26
- **Plugin version**: 0.2.9

### 问题详情

（咨询）

你好，

请问是否能够永久设置界面显示的字体大小，不用在每次翻译内容后重新放大界面字体。

谢谢！

**Comment by MuiseDestiny** [comment]
后面加入记忆

**Comment by zichunxx** [comment]
> 后面加入记忆

是后续功能吗？
