### ISSUE TITLE
请教一个关于token的问题

### ISSUE THREAD

**Issue by lemonade7296** [MuiseDestiny/zotero-gpt#171]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

在使用过程中经常出现一个问题就是token数量超出了最大的限制，作者大佬给出的解决办法是/clear。
我不是很清楚这个操作具体做了什么，clear之后会需要重新上传文章的内容么？
以及我在一篇文章A使用之后，打开另一篇B，之后又回到这一篇A进行提问还会重新上传文章内容么？
有重新按token计费上传的时间间隔么？
这个对话最大限制包含了包含了什么东西？或者说哪些内容会被算到这个限制数量内？是不是包含了返回的5（默认值）个相关最强段落，因为我感觉很多时候回答的字数是远小于限制的token数量的。
还有，我该怎么知道tag内部那些变量的含义？比如Meet.Global.views.messages[0].content这是什么部分？我想自己做几条更适合自己的tag。

问题太多了，非常抱歉，我只看了一些openai api的皮毛，打搅大家了。

**Comment by MuiseDestiny** [comment]
clear会清除历史会话。不会重新上传。Meet.Global.views.messages[0].content这是所有对话的第一条的内容。更多内容参考源码。

**Comment by lemonade7296** [comment]
哦哦，好的，谢谢大佬
