### ISSUE TITLE
无法设置api和secretKey

### ISSUE THREAD

**Issue by anrgct** [MuiseDestiny/zotero-gpt#172]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: mac 11.5.2
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.9

### 当前配置信息

api https://api.openai.com
secretKey …
model gpt-3.5-turbo
temperature 1.0

### 问题详情

我想使用api2d设置api和secretKey，我输入/secretKey之后，输入fkxxx，回车，好像在请求中，无法设置到插件里，api也是同理，似乎是需要请求成功才可以设置？那api和secretKey两个必须先设置一个，另一个请求时才能成功

**Comment by MuiseDestiny** [comment]
请截图，或者录屏。你的描述感觉不可能出现。

**Comment by anrgct** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/16172523/f749a585-ff16-4724-b249-6988fb1ffccd)
补充图片

**Comment by MuiseDestiny** [comment]
其他设置同理

**Comment by anrgct** [comment]
感谢！

**Comment by llity** [comment]
@MuiseDestiny 清空API 和Key 怎么操作的哦。谢谢

**Comment by MuiseDestiny** [comment]
> @MuiseDestiny 清空API 和Key 怎么操作的哦。谢谢

/secretKey default

清空去高级编辑器吧

**Comment by llity** [comment]
谢谢 👍 )
