### ISSUE TITLE
在mac系统里，无法拖动，改变窗口大小，以及因为无鼠标，通过双击右键这种方式无法删除标签

### ISSUE THREAD

**Issue by ZhaoYanQ** [MuiseDestiny/zotero-gpt#173]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Mac os 10.14.6
- **Zotero version**:  6.0.26
- **Plugin version**:  0.2.9

### 问题详情

在mac系统里，因为无鼠标，只能通过单指（左击）、双指（右击）、三指（左击长按）这些方式完成点击
在这情形下，无法拖动，改变窗口大小；若是按下command键可拖动，但之后会随着鼠标运动，即使啥都不按
通过双击右键这种方式无法删除标签，会导致直接运行（与单击效果相似）
还有一个小问题，在zotero回答完问题后会 zoterogpt窗口会自动退出

**Comment by MuiseDestiny** [comment]
> 在zotero回答完问题后会 zoterogpt窗口会自动退出

更新一下gpt插件，Better notes插件（如果有）。

> 若是按下command键可拖动，但之后会随着鼠标运动

本身就是ctrl+鼠标移动的。

> 双击右键这种方式无法删除标签

长按右键删除，不是双击

**Comment by ZhaoYanQ** [comment]
Mac系统中，触控板的双指点按是右键的意思，但这无法删除标签，会导致直接运行（与单指操作效果相似），即使换成点击触控板的右下角完成右键操作的方式，也依旧无法删除标签

**Comment by MuiseDestiny** [comment]
双指按下不松开
