### ISSUE TITLE
Cannot find module '../../validation/core'

### ISSUE THREAD

**Issue by lyk7539511** [MuiseDestiny/zotero-gpt#174]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Macos 13
- **Zotero version**:  6.0.26
- **Plugin version**:  0.2.9

### 问题详情

编译出错，✘ [ERROR] Could not resolve "../../validation/core"
请问相关文件在哪里

➜ /workspaces/zotero-gpt (bootstrap) $ npm install

added 24 packages, changed 7 packages, and audited 734 packages in 3s

237 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

➜ /workspaces/zotero-gpt (bootstrap) $ npm run build

> zotero-gpt@0.2.8 build
> concurrently -c auto npm:build-prod npm:tsc

[tsc] 
[tsc] > zotero-gpt@0.2.8 tsc
[tsc] > tsc --noEmit
[tsc] 
[build-prod] 
[build-prod] > zotero-gpt@0.2.8 build-prod
[build-prod] > cross-env NODE_ENV=production node scripts/build.js
[build-prod] 
[build-prod] [Build] BUILD_DIR=builds, VERSION=0.2.8, BUILD_TIME=2023-06-05 14:26:11, ENV=production
[build-prod] ✘ [ERROR] Could not resolve "../../validation/core"
[build-prod] 
[build-prod]     src/hooks.ts:5:31:
[build-prod]       5 │ import { initValidation } from "../../validation/core";
[build-prod]         ╵                                ~~~~~~~~~~~~~~~~~~~~~~~
[build-prod] 
[build-prod] npm run build-prod exited with code 1
[tsc] src/hooks.ts(5,32): error TS2307: Cannot find module '../../validation/core' or its corresponding type declarations.
[tsc] npm run tsc exited with code 2

**Comment by MuiseDestiny** [comment]
注释掉 "../../validation/core"这行，没有用到它

**Comment by homeofmny** [comment]
> ### 这个问题是否已有issue
> * [x]  我确认没有已有issue，且已阅读**常见问题**
> 
> ### 运行环境
> * **OS**:  Macos 13
> * **Zotero version**:  6.0.26
> * **Plugin version**:  0.2.9
> 
> ### 当前配置信息
> _No response_
> 
> ### 问题详情
> 编译出错，✘ [ERROR] Could not resolve "../../validation/core" 请问相关文件在哪里
> 
> ➜ /workspaces/zotero-gpt (bootstrap) $ npm install
> 
> added 24 packages, changed 7 packages, and audited 734 packages in 3s
> 
> 237 packages are looking for funding run `npm fund` for details
> 
> found 0 vulnerabilities
> 
> ➜ /workspaces/zotero-gpt (bootstrap) $ npm run build
> 
> > zotero-gpt@0.2.8 build
> > concurrently -c auto npm:build-prod npm:tsc
> 
> [tsc] [tsc] > zotero-gpt@0.2.8 tsc [tsc] > tsc --noEmit [tsc] [build-prod] [build-prod] > zotero-gpt@0.2.8 build-prod [build-prod] > cross-env NODE_ENV=production node scripts/build.js [build-prod] [build-prod] [Build] BUILD_DIR=builds, VERSION=0.2.8, BUILD_TIME=2023-06-05 14:26:11, ENV=production [build-prod] ✘ [ERROR] Could not resolve "../../validation/core" [build-prod] [build-prod] src/hooks.ts:5:31: [build-prod] 5 │ import { initValidation } from "../../validation/core"; [build-prod] ╵ ~~~~~~~~~~~~~~~~~~~~~~~ [build-prod] [build-prod] npm run build-prod exited with code 1 [tsc] src/hooks.ts(5,32): error TS2307: Cannot find module '../../validation/core' or its corresponding type declarations. [tsc] npm run tsc exited with code 2
> 
> ### 补充说明
> _No response_

@lyk7539511 你好，请问一下你编译成功了吗？我注释掉后虽然编译成功，但是无法在Zotero运行，错误日志中显示WeakRef is not defined，想问一下你编译后的插件是正常的吗？

**Comment by lyk7539511** [comment]
> > ### 这个问题是否已有issue
> > 
> > * [x]   我确认没有已有issue，且已阅读**常见问题**
> > 
> > ### 运行环境
> > 
> > * **OS**:  Macos 13
> > * **Zotero version**:  6.0.26
> > * **Plugin version**:  0.2.9
> > 
> > ### 当前配置信息
> > _No response_
> > ### 问题详情
> > 编译出错，✘ [ERROR] Could not resolve "../../validation/core" 请问相关文件在哪里
> > ➜ /workspaces/zotero-gpt (bootstrap) $ npm install
> > added 24 packages, changed 7 packages, and audited 734 packages in 3s
> > 237 packages are looking for funding run `npm fund` for details
> > found 0 vulnerabilities
> > ➜ /workspaces/zotero-gpt (bootstrap) $ npm run build
> > > zotero-gpt@0.2.8 build
> > > concurrently -c auto npm:build-prod npm:tsc
> > 
> > 
> > [tsc] [tsc] > zotero-gpt@0.2.8 tsc [tsc] > tsc --noEmit [tsc] [build-prod] [build-prod] > zotero-gpt@0.2.8 build-prod [build-prod] > cross-env NODE_ENV=production node scripts/build.js [build-prod] [build-prod] [Build] BUILD_DIR=builds, VERSION=0.2.8, BUILD_TIME=2023-06-05 14:26:11, ENV=production [build-prod] ✘ [ERROR] Could not resolve "../../validation/core" [build-prod] [build-prod] src/hooks.ts:5:31: [build-prod] 5 │ import { initValidation } from "../../validation/core"; [build-prod] ╵ ~~~~~~~~~~~~~~~~~~~~~~~ [build-prod] [build-prod] npm run build-prod exited with code 1 [tsc] src/hooks.ts(5,32): error TS2307: Cannot find module '../../validation/core' or its corresponding type declarations. [tsc] npm run tsc exited with code 2
> > ### 补充说明
> > _No response_
> 
> @lyk7539511 你好，请问一下你编译成功了吗？我注释掉后虽然编译成功，但是无法在Zotero运行，错误日志中显示WeakRef is not defined，想问一下你编译后的插件是正常的吗？

我也忘记我当时是怎么解决的了，不好意思

**Comment by panwanke** [comment]
注释之后成功编译，但是将xpi导入zotero时显示：它可能无法与该版本的 Zotero 兼容。我使用的是 7.0.0-beta.54+6b996d4f9 (64-bit)。 windows 11 平台。 @MuiseDestiny

**Comment by tigerwangping** [comment]
我编译的0.2.9的src， 也是出现同样的问题，
Cannot find module '../../validation/core'
注释掉后，还出现src/hooks.ts(8,3): error TS2304: Cannot find name 'initValidation'. 把后面的initValidation(config.addonRef); 这行也注释掉，能编译成功，但是将xpi导入zotero后，无法启动。
