### ISSUE TITLE
配置过密钥后在使用插件时被反复提示request time out是因为什么原因呢，求解答。

### ISSUE THREAD

**Issue by AlexanderIlia1996** [MuiseDestiny/zotero-gpt#178]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/136436869/5e65c801-19d3-4d4a-a55a-b67d7fa454f3)

**Comment by MuiseDestiny** [comment]
美国的服务，大陆的网络无法抵达，全局代理

**Comment by AlexanderIlia1996** [comment]
请问这个全局代理具体应该怎么设置啊，我用了梯子，是在Zotero里也要设置一遍吗。

**Comment by AlexanderIlia1996** [comment]
> 美国的服务，大陆的网络无法抵达，全局代理

请问这个全局代理具体应该怎么设置啊，我用了梯子，是在Zotero里也要设置一遍吗。

**Comment by MuiseDestiny** [comment]
> > 美国的服务，大陆的网络无法抵达，全局代理
> 
> 请问这个全局代理具体应该怎么设置啊，我用了梯子，是在Zotero里也要设置一遍吗。

梯子全局即可，zotero自动识别代理

**Comment by AlexanderIlia1996** [comment]
> 

我用的是Ghelper，请问这个插件可以设置全局代理吗，没有找到合适的方法。

**Comment by AlexanderIlia1996** [comment]
> > > 美国的服务，大陆的网络无法抵达，全局代理
> > 
> > 
> > 请问这个全局代理具体应该怎么设置啊，我用了梯子，是在Zotero里也要设置一遍吗。
> 
> 梯子全局即可，zotero自动识别代理

解决啦，非常感谢。

**Comment by tonitsk-8264** [comment]
我用的也是Ghelper，麻烦问一下你是怎么解决的呀 @AlexanderIlia1996
