### ISSUE TITLE
What is the capability of this plugin to handle large pdf files?

### ISSUE THREAD

**Issue by zhechenghu** [MuiseDestiny/zotero-gpt#182]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 13.3.1 (a) (22E772610a)
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.9

### 问题详情

我对一个1400页的pdf文件使用了askPDF功能。然后它卡住了。希望知道大概最多能处理多大的文件？

**Comment by MuiseDestiny** [comment]
> 我对一个1400页的pdf文件使用了askPDF功能。然后它卡住了。希望知道大概最多能处理多大的文件？

无限大。只是看电脑内存了。1400页有可能内存不足。或者处理大量向量卡死。

**Comment by MuiseDestiny** [comment]
我试过300+页的三国演义。再多没有测试过

**Comment by zhechenghu** [comment]
感谢您的快速回复！我明白了，那我就关闭这个issue了
