### ISSUE TITLE
插件配置信息在哪里修改

### ISSUE THREAD

**Issue by Fatebro** [MuiseDestiny/zotero-gpt#187]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 22H2
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.9

### 问题详情

我想找到该插件的配置文件位置，

**Comment by MuiseDestiny** [comment]
输入/help回车
