### ISSUE TITLE
答复与选中文本无关

### ISSUE THREAD

**Issue by Corey01327** [MuiseDestiny/zotero-gpt#188]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Mac 13.3
- **Zotero version**:6.0.26 
- **Plugin version**: 0.2.9

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...eWQk
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

我选中一段文本，问”如何理解这段话“
答案是将全文作了输入，然后总结全文了

**Comment by Corey01327** [comment]
重复实验之后，好像是选中的文本无法被插件识别到

**Comment by MuiseDestiny** [comment]
下面有个selection标签按钮

**Comment by MuiseDestiny** [comment]
你想让他继续选中内容回答，需要点击selection

**Comment by Corey01327** [comment]
> 你想让他继续选中内容回答，需要点击selection

哦哦哦！好的，测试了一下，成功了
大佬请问一下，视频《Zotero GPT - 一个游走于文献间的精灵》中选中文本之后，选择“解释”、“总结”的那个功能是怎么实现的呢
