### ISSUE TITLE
insufficient_quota

### ISSUE THREAD

**Issue by wangleping2000** [MuiseDestiny/zotero-gpt#201]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Win10
- **Zotero version**: 6.0.26
- **Plugin version**: 0.3.0

### 当前配置信息

'api' https://api.openai.com/v1
'model' gpt-3.5-turbo
'temperature' 1.0

### 问题详情

报错如下
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/87556341/bec837af-2a63-4adb-be33-e114e71ebbb9)

### 补充说明

每篇PDF都有问题

**Comment by MuiseDestiny** [comment]
你的号没钱了

**Comment by wangleping2000** [comment]
不是一个key可以永久使用吗
