### ISSUE TITLE
insufficient_quota but gpt-4

### ISSUE THREAD

**Issue by BeckyYhui** [MuiseDestiny/zotero-gpt#202]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Mac OS
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.9

### 当前配置信息

api https://api.openai.com
secretKey sk-…bp9q
model gpt-3.5-turbo
temperature 1.0

### 问题详情

在海外使用,api是自己账号的，并且付费gpt4.0
报错insufficient_quota（图1）, 复制报错链接在chrome打开后如图2
<img width="363" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/130902598/b3083a43-1202-47d5-90f1-27b532005c16">
<img width="704" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/130902598/0b41a5ee-a0d3-4b12-8374-7acaa920f498">
gpt-4是可以正常使用的
<img width="988" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/130902598/3f960cd3-03e2-4144-bb0f-4ec527d805ac">

换了另一个只有没付费的open ai账号的api仍然显示insufficient-quota

麻烦大佬帮忙看看哪里有问题？感谢！！

### 补充说明

稳定复现，还没办法开始使用

**Comment by MuiseDestiny** [comment]
> gpt-4是可以正常使用的

chatGPT是gpt的一个应用，只要有号就可以用。gpt-4的api额度是另外算钱的。

**Comment by wangxiaofeng93** [comment]
> 

gpt-3也出现这个问题呢？gpt-3的api额度也是另外算钱的吗

**Comment by MuiseDestiny** [comment]
> gpt-3也出现这个问题呢？gpt-3的api额度也是另外算钱的吗

都是的

**Comment by BeckyYhui** [comment]
您的意思是除了gpt-plus还需要另外购买api来调用吗？

**Comment by Duan123rh** [comment]
我也遇到了，还不如不添加API的时候，现在完全不能用了

**Comment by Duan123rh** [comment]
可以取消API吗……

**Comment by MuiseDestiny** [comment]
> 可以取消API吗……

/secretKey default

**Comment by tonlylam** [comment]
> > 可以取消API吗……
> 
> /secretKey default

键入上述命令后，点ask pdf变成了“Your secretKey is not configured.”，依旧不可用（是我的用法有问题吗
<img width="290" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/38854412/7bcaa1b7-b38c-48e5-9f6e-26bd8457bcde">

**Comment by aaalu26** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/96238215/39f1b256-9216-4d37-932b-17ed227a43e1)
我也遇到这个问题，仔细阅读了一下官网发现API有试用期（好像是3个月），过了试用期就要自己购买API额度。API额度和是否购买gpt-4没有关系。
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/96238215/b63b1654-6d9b-41ee-91d9-ccad2813e3fb)

**Comment by Duan123rh** [comment]
嗯嗯，今天看了一下的确如此。谢谢。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: aaalu26 ***@***.***>
发送时间: Tuesday, August 29, 2023 9:17:44 PM
收件人: MuiseDestiny/zotero-gpt ***@***.***>
抄送: Duan123rh ***@***.***>; Comment ***@***.***>
主题: Re: [MuiseDestiny/zotero-gpt] insufficient_quota but gpt-4 (Issue #202)


[image]<https://user-images.githubusercontent.com/96238215/264030764-39f1b256-9216-4d37-932b-17ed227a43e1.png>
我也遇到这个问题，仔细阅读了一下官网发现API有试用期（好像是3个月），过了试用期就要自己购买API额度。API额度和是否购买gpt-4没有关系。
[image]<https://user-images.githubusercontent.com/96238215/264031396-b63b1654-6d9b-41ee-91d9-ccad2813e3fb.png>

―

**Comment by zwbx** [comment]
希望能够增加适配chatGPT的版本,不需要使用api
