### ISSUE TITLE
zoteroGPT所有命令标签都提示出错——在确认梯子可用，chatGPT可访问的前提下

### ISSUE THREAD

**Issue by Bellamagic** [MuiseDestiny/zotero-gpt#206]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: macOS Monterey 12.3
- **Zotero version**: 6.0.26
- **Plugin version**: 0.2.9

### 当前配置信息

api https://chat.openai.com
secretKey sk-…e0Ye
model gpt-3.5-turbo
temperature 1.0

### 问题详情

所有的命令标签点击后都报错

**Comment by MuiseDestiny** [comment]
太抽象了。请详细描述，目前无法提供帮助。

**Comment by Bellamagic** [comment]
提示error如图所示，盼回复，非常感谢！祝好！




DADA贝
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MuiseDestiny/zotero-gpt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月24日(星期一) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MuiseDestiny/zotero-gpt] zoteroGPT所有命令标签都提示出错——在确认梯子可用，chatGPT可访问的前提下 (Issue #206)





 
太抽象了。请详细描述，目前无法提供帮助。

**Comment by Bellamagic** [comment]
<img width="274" alt="截屏2023-07-24 10 09 30的副本" src="https://github.com/MuiseDestiny/zotero-gpt/assets/113834301/b6afaa93-d770-4531-9b37-4828b357d2d0">

**Comment by MuiseDestiny** [comment]
你的api配置有误https://github.com/MuiseDestiny/zotero-gpt/wiki/secretKey%E5%92%8Capi%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by Bellamagic** [comment]
具体是哪里有误呢？

**Comment by Bellamagic** [comment]
已发现，谢谢！

**Comment by Genesislin** [comment]
使用梯子后，zotero的插件无法使用，而gpt就需要梯子
