### ISSUE TITLE
网络配置可以访问chatgpt，且可以直接在chrome中访问api,但是zotero-gpt始终报错requtest time out

### ISSUE THREAD

**Issue by aweng126** [MuiseDestiny/zotero-gpt#208]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS **: MacOS 
- **Zotero version**:6.0.26 
- **Plugin version**: 0.3.0

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...Ry95
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

网络配置可以访问chatgpt网页，且可以直接在chrome中访问实际请求的api接口,但是zotero-gpt始终报错requtest time out. 
查看目前插件给的日志并未发现问题所在。
报错截图：
<img width="322" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/fddee6db-364d-44d9-b610-d343bb9903be">
日志截图
<img width="978" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/85341433-0f08-4ed4-8e88-529ca4ef919c">
浏览器直接访问api接口结果截图
<img width="1370" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/609dc83a-6edd-4a19-8742-f859b0d4ad90">

**Comment by MuiseDestiny** [comment]
可以访问chatgpt网页 **不等于** 你的密钥有额度。

**Comment by MuiseDestiny** [comment]
访问：https://platform.openai.com/account/usage

有额度的截图：
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/b9e6db6f-2c2b-4c8f-9465-22defc925b11)

无额度的截图：
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/da99e720-78a1-4e1e-bc14-d623b904cf78)

**Comment by MuiseDestiny** [comment]
> zotero-gpt始终报错requtest time out

开启全局代理

**Comment by aweng126** [comment]
> Reference

已经在处理了，等成功了再来回复。

**Comment by aweng126** [comment]
<img width="907" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/ed0c57c5-557f-4cf9-889a-60bf0299aa4c">
done！
