### ISSUE TITLE
当选择一个文件夹最下面的文献时，回复窗口依然会显示在最下面导致窗口不可见

### ISSUE THREAD

**Issue by csf2022scut** [MuiseDestiny/zotero-gpt#21]
![image](https://user-images.githubusercontent.com/117445516/229003126-c92ebaf6-bac2-4d35-855b-db1312df14e5.png)

**Comment by MuiseDestiny** [comment]
你可以先选择靠上的条目，唤醒它，然后选中最后一个问他。然后等待修复这个bug。

**Comment by csf2022scut** [comment]
好的，谢谢！

**Comment by kettly1260** [comment]
还有就是如果翻译太长的话就看不到了，这时候还没办法按最下面拖动窗口
