### ISSUE TITLE
encountered end of file,error code: PR_END_OF_FILE_ERROR

### ISSUE THREAD

**Issue by aweng126** [MuiseDestiny/zotero-gpt#211]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Mac OS 
- **Zotero version**: 6.0.26 
- **Plugin version**: 0.3.0

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...j1cC
`model` gpt-3.5-turbo
`temperature` 1.0

### 问题详情

请求的时候始终会碰到End of error 问题。无论是直接输入hello,还是点击translate.都会持续出现这个问题。
<img width="268" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/274a4adc-cd2a-48cb-90cc-b20e35f3399f">

**Comment by MuiseDestiny** [comment]
或许和网络有关

**Comment by aweng126** [comment]
> 或许和网络有关

有没有什么办法可以检查一下呢？有定位问题产生原因的思路吗?

**Comment by MuiseDestiny** [comment]
> > 或许和网络有关
> 
> 有没有什么办法可以检查一下呢？有定位问题产生原因的思路吗?

你的代理可以打开全局

**Comment by aweng126** [comment]
> > > 或许和网络有关
> > 
> > 
> > 有没有什么办法可以检查一下呢？有定位问题产生原因的思路吗?
> 
> 你的代理可以打开全局

代理打开全局模式了，可以正常访问chatgpt聊天页面，然后用咱们插件request timeout 和 pr_end_of_file轮流出现。很奇怪。这这是对应的日志截图，你看看是否有问题存在。
<img width="929" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/13829182/c05b446e-a071-4368-930e-24b5f6cc8470">

**Comment by MuiseDestiny** [comment]
发todesk远程控制码，不要发密码，仅仅控制码

**Comment by aweng126** [comment]
> 发todesk远程控制码，不要发密码，仅仅控制码

ToDesk:
设备代码:730 097 601

**Comment by aweng126** [comment]
原因网络代理有问题，更换代理即可解决。感谢 @MuiseDestiny

**Comment by Zhuxiaohuo** [comment]
求解决，我一直显示PR END OF FILE ERROR
