### ISSUE TITLE
[Bug] zotero7安装插件后无法使用

### ISSUE THREAD

**Issue by BoBo-YunYun** [MuiseDestiny/zotero-gpt#216]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

OS: Windows11 22H2
Zotero version: 7.0.0-beta.27+07309d7c2 (64-bit)
Plugin version: 0.3.0

### 问题详情

up好，我的附加组件里显示安装成功zotero GPT，但是首选项里没有zotero GPT，使用界面里也没有那个zotero GPT图标

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/121593119/c055bb51-6f2f-4636-b039-70f79ff6b7cd)

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/121593119/cf761837-5967-4a4d-8581-644bffbf44e8)

**Comment by MuiseDestiny** [comment]
首选项本身就是没有的。不是所有插件都有这个设置界面。请阅读readme后使用

**Comment by BoBo-YunYun** [comment]
好的好的，我直接下了个xpi用了，谢谢up
