### ISSUE TITLE
AskPDF没有阅读PDF

### ISSUE THREAD

**Issue by coder-chenzhi** [MuiseDestiny/zotero-gpt#217]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows 11
- **Zotero version**: 6.0.26
- **Plugin version**:  0.2.9

### 当前配置信息

https://api.openai.com
 sk-…n6Mw
 gpt-3.5-turbo-16k
 1.0

### 问题详情

从右下角弹窗日志里可以看到，根本没有阅读PDF
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/3889660/25fa0daa-db72-4a81-97e0-c63aab9d7ed3)

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/3889660/c3142143-3d41-414b-87f6-7ba3bc19928b)

### 补充说明

试了很多文献调用AskPDF，都没有阅读PDF

**Comment by MuiseDestiny** [comment]
Askpdf
打开pdf后使用
