### ISSUE TITLE
今天（2023年8月8日）一打开插件，无法使用，还提示You exceeded your current quota

### ISSUE THREAD

**Issue by Myoontyee** [MuiseDestiny/zotero-gpt#218]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows10 21H2
- **Zotero version**:  6.0.26
- **Plugin version**:  0.2.9

### 当前配置信息

api https://api.openai.com
secretKey sk-…qD61
model gpt-3.5-turbo
temperature 1.0

### 问题详情

2023年8月8日
2台电脑、2个账号都试了，今天一打开就是这样，说超额了
这是openai的问题？还是插件需要更新？可是插件已经是最新版了
![图片](https://github.com/MuiseDestiny/zotero-gpt/assets/40823733/2b4e8898-4228-44d8-adfc-84694235a277)

### 补充说明

稳定复现该问题。在[知乎页面](https://zhuanlan.zhihu.com/p/619798604)也发现了很多人遇上这种情况
![图片](https://github.com/MuiseDestiny/zotero-gpt/assets/40823733/e9b8602f-7b45-4af2-8317-687a7c1bc330)

**Comment by leewaro** [comment]
我用自己的秘钥也无法使用，请问您解决了吗

**Comment by Myoontyee** [comment]
> 我用自己的秘钥也无法使用，请问您解决了吗

我怀疑是OpenAI的问题，也等作者过来看看情况咋样

**Comment by MuiseDestiny** [comment]
你的api 密钥没有费用了，与插件无关
