### ISSUE TITLE
点击“添加摘要标签”后回复代码而不是添加标签

### ISSUE THREAD

**Issue by hujie12306** [MuiseDestiny/zotero-gpt#22]
![image](https://user-images.githubusercontent.com/61086637/229020737-33c87e93-e3f8-413f-95a5-168bebfa84c0.png)

**Comment by MuiseDestiny** [comment]
长按约束一下它，让它只输出代码

**Comment by hujie12306** [comment]
解决了，如下

#添加摘要标签[c=#7149C6][pos=1]
现在请你从下面的摘要中分析出三个标签：
```js
i = ZoteroPane.getSelectedItems()[0];
i.getField("abstractNote");
```
然后给我一段代码用于向Zotero选中条目添加你分析出的标签，仅回复代码，不要添加Here's the code with the three tags l identified。示例代码如下：

i = ZoteroPane.getSelectedItems()[0];
tags = ["tag1", "tag2"];
tags.forEach(tag=>i.addTag(tag));
await i.saveTx();

**Comment by MuiseDestiny** [comment]
简单粗暴哈
