### ISSUE TITLE
gpt插件运行过程中显示冲突

### ISSUE THREAD

**Issue by ihahya** [MuiseDestiny/zotero-gpt#228]
zotero-7
插件-0.3.1
在GPT回答生成过程中跳出弹窗
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/129815867/d137bd6e-6e8c-408a-a093-9f918757fdcb)

**Comment by ihahya** [comment]
停止运行gpt插件后还是不停跳出

**Comment by MuiseDestiny** [comment]
这是style的进度同步吧
跟gpt插件无关。首选项style storage设置成file就可以了

**Comment by ihahya** [comment]
好的了解了，谢谢
