### ISSUE TITLE
回答问题后内容马上消失，没机会双击复制回答的内容~~

### ISSUE THREAD

**Issue by skipskipthree** [MuiseDestiny/zotero-gpt#231]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **win11**: 
- **Zotero 7 b39**: 
- **Plugin version0.3.2**: 

### 当前配置信息

aip
key

### 问题详情

选中内容后，点击标签顺利翻译，askpdf也能顺利回答。但是，翻译完和回答问题结束后，翻译的内容马上消失。。。。

### 补充说明

该问题稳定复现

**Comment by ncu-walker** [comment]
你好，碰到相同的问题，你是怎么解决的？

**Comment by skipskipthree** [comment]
> 你好，碰到相同的问题，你是怎么解决的？

不用最新的插件，换的第一版适用z7的那个
