### ISSUE TITLE
插件出大问题了，tags都不能用了，有没有恢复默认设置的功能。

### ISSUE THREAD

**Issue by HMethod** [MuiseDestiny/zotero-gpt#237]
### 这个问题是否已有issue

- [ ] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Mac
- **Zotero version**: 7.0.0-beta.39+ecba25be0
- **Plugin version**: 0.3.2

### 问题详情

improve writing 不能用了![截屏2023-09-17 19 53 42](https://github.com/MuiseDestiny/zotero-gpt/assets/100885871/0d147f10-87b1-4554-bc28-2514cd8265a1)
AskPDF也不能直接读取文章。
![截屏2023-09-17 20 01 14](https://github.com/MuiseDestiny/zotero-gpt/assets/100885871/9caed3fc-5ada-4580-995a-50e41b222b17)
翻译也不能用了
![截屏2023-09-17 20 02 23](https://github.com/MuiseDestiny/zotero-gpt/assets/100885871/81932583-f5de-42a5-8430-801672cc1bbd)

**Comment by HMethod** [comment]
fixed

**Comment by MuiseDestiny** [comment]
升级zotero软件，升级插件。
