### ISSUE TITLE
zotero GPT无法启用的问题

### ISSUE THREAD

**Issue by TTTonyPRS** [MuiseDestiny/zotero-gpt#239]
提示报错：
HTTP POST
https://api.chatanywhere.com.cn
/v1/chat/completions failed with status code 401: <!DOCTYPE HTML
PUBLIC "-//IETF//DTD HTML
2.0//EN"> <html> <head> <title > 401
Authorization Required </title> </head> <body> <h1>401
Authorization Required </h1 > <p> This server could not verify that you are authorized to access the document requested. <hr/> Powered by Tengine</body> </html>

**Comment by zfb132** [comment]
联系 [api.chatanywhere.com.cn](https://api.chatanywhere.com.cn/) 的管理人员，确认他们搭建的接口的正确使用方法。根据报错猜测是你的 `secretKey` 不正确

**Comment by haihy** [comment]
> 联系 [api.chatanywhere.com.cn](https://api.chatanywhere.com.cn/) 的管理人员，确认他们搭建的接口的正确使用方法。根据报错猜测是你的 `secretKey` 不正确

感谢，根据你的提示重新配置一遍。可以了
