### ISSUE TITLE
如何禁用点击自动 copy 功能

### ISSUE THREAD

**Issue by hannah037** [MuiseDestiny/zotero-gpt#241]
请问，是否有什么设置，可以让我关闭点击"回答自动 copy到better notes笔记界面"的功能
谢谢

**Comment by MuiseDestiny** [comment]
你手动复制即可，不要双击。

**Comment by hannah037** [comment]
> 你手动复制即可，不要左侧。
只要点到那个地方，就会自动 copy 到笔记区域，单击就会

**Comment by hannah037** [comment]
> 你手动复制即可，不要双击。

只要点到那个地方，就会自动 copy 到笔记区域，单击就会
