### ISSUE TITLE
打不开插件，Reference error: console is not defined

### ISSUE THREAD

**Issue by jiagengliu** [MuiseDestiny/zotero-gpt#243]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: M1 macOS Ventura
- **Zotero version**: 7.0.0-beta.41+aef49da23
- **Plugin version**: 0.2.9

### 当前配置信息

打不开插件

### 问题详情

安装了，出现了GPT按钮，但是点击无反应。用快捷键同样没有反应。Browser error如下

ReferenceError: console is not defined [Learn More]
TypeError: this.gViewSourceUtils is undefined [Learn More]
viewSource
resource://devtools/client/webconsole/webconsole.js:225
onViewSource
resource://devtools/client/webconsole/service-container.js:43
onClick
resource://devtools/client/shared/components/Frame.js:259
• React 19
dispatchInteractiveEvent self-hosted: 1162

**Comment by MuiseDestiny** [comment]
可是最新的是0.3.2

https://github.com/MuiseDestiny/zotero-gpt/releases/tag/0.3.2
