### ISSUE TITLE
Gpt回答在最后面会产生乱码

### ISSUE THREAD

**Issue by z2332677** [MuiseDestiny/zotero-gpt#246]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 23H2
- **Zotero version**: 7.0.0-beta.43+5e634f57f (64-bit)
- **Plugin version**: 0.3.2

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...k2VV
`model` gpt-3.5-turbo
`temperature` 2.0

### 问题详情

不管是第三方接口或者官网接口，回答都存在乱码现象
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/73976364/5465ed7b-243b-4bf8-8327-5d926a72bc9a)

### 补充说明

可以稳定复现，跟pdf文件无关（关闭zotero，重启也是）

**Comment by zfb132** [comment]
可能是openai官方的bug，现在重新尝试是否还能复现？

**Comment by z2332677** [comment]
并没有解决，还能复现

**Comment by z2332677** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/73976364/a3b991a4-6934-4e5a-9a08-3038c38799e3)

**Comment by zfb132** [comment]
刚复现了你的问题，这是由于`temperature = 2`引起的，你把它改成`1`即可

**Comment by z2332677** [comment]
谢谢~，解决了
