### ISSUE TITLE
This model’s maximum context length is 4097 tokens. However, your messages resulted in 6596 tokens. Please reduce the length of the messages.

### ISSUE THREAD

**Issue by 15153462274** [MuiseDestiny/zotero-gpt#247]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **win**: 
- **Zotero version**: 
- **Zotero GPT 0.2.9**: 

### 问题详情

![屏幕截图 2023-10-04 162310](https://github.com/MuiseDestiny/zotero-gpt/assets/142067819/fcd8b4f9-a639-45b4-a7e6-e8a71c91be9b)
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/142067819/786f1bed-5258-4c9b-84d2-b3fadc1b8b6b)

随便问点问题就这样了

**Comment by zfb132** [comment]
`chatNumber`不应该太大，尝试修改为`5`或者`10`。另外，你可以换用支持更长上下文的模型，而不是`gpt-3.5-turbo`

**Comment by 15153462274** [comment]
> `chatNumber`不应该太大，尝试修改为或者。另外，你可以换用支持更长上下文的模型，而不是`5``10``gpt-3.5-turbo`

谢谢哈
