### ISSUE TITLE
This add-on seems not to use Zotero's proxy settings?

### ISSUE THREAD

**Issue by cychen2021** [MuiseDestiny/zotero-gpt#25]
I've set proxy in Zotero's preferences, but I didn't see any request to openai by this add-on in my proxy's panel.

**Comment by cychen2021** [comment]
Solved. Set the `network.proxy.ssl` and `network.proxy.ssl_port` options.

**Comment by MuiseDestiny** [comment]
> Solved. Set the proxy_on_ssl option.

Sorry I wasn't able to help.
