### ISSUE TITLE
askpdf回答出来的是代码相关

### ISSUE THREAD

**Issue by ChukieWu** [MuiseDestiny/zotero-gpt#258]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 14.0 (23A344)
- **Zotero version**: 7.0.0-beta.46+c27bac2ad
- **Plugin version**: 0.3.2

### 当前配置信息

`api` https://api.openai.com
`secretKey` sk-...u3K6
`model` gpt-3.5-turbo-16k
`temperature` 1.0

### 问题详情

输出是这样：根据提供的上下文信息中的代码，我们可以看出正在处理的是一个全局消息数组，并且正在调用Meet.Zotero.getRelatedText函数来获取与输入相关的文本。然而，代码内部并没有明确提到正在处理的具体文献，因此无法给出这篇文献的创新点 [1]。要获得关于特定文献的创新点，需要提供更多关于该文献的信息。

**Comment by zfb132** [comment]
长按标签进入编辑模式，确保每个标签的内容如下  
https://github.com/MuiseDestiny/zotero-gpt/blob/e80732367f6804f7c36a8403a1ff026403e6eeee/src/modules/base.ts#L85-L162

**Comment by zfb132** [comment]
重复问题，请在另一个问题下回复
