### ISSUE TITLE
如果要设置4.0的话，model应该怎么设置

### ISSUE THREAD

**Issue by Andy2088** [MuiseDestiny/zotero-gpt#261]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 操作系统：Windows11 22H2
佐特罗版本：6.0.23
插件版本：0.2.3
- **Zotero version**: 
- **Plugin version**: 

### 当前配置信息

操作系统：Windows11 22H2
佐特罗版本：6.0.23
插件版本：0.2.3

### 问题详情

操作系统：Windows11 22H2
佐特罗版本：6.0.23
插件版本：0.2.3

### 补充说明

操作系统：Windows11 22H2
佐特罗版本：6.0.23
插件版本：0.2.3

**Comment by zfb132** [comment]
首先建议插件版本使用`0.2.9`，其次你可以在`zotero gpt`的输入框输入`/model gpt-4`并回车即可

**Comment by Yongzhaooo** [comment]
> 首先建议插件版本使用`0.2.9`，其次你可以在`zotero gpt`的输入框输入`/model gpt-4`并回车即可

麻烦请教一下，我在编辑里面已经把两个gpt model都设置为gpt-4了，但是无论是我直接问GPT还是在GPT的操作面板上看，我都没有成功调用4，依然是3.5turbo（已付费5美元解锁4）。请问这个可能是什么地方没设置好呢？

<img width="588" alt="Snipaste_2023-11-08_09-44-51" src="https://github.com/MuiseDestiny/zotero-gpt/assets/133014490/ba439196-76ea-4fab-a50a-3bfe7c8f6a37">
<img width="544" alt="Snipaste_2023-11-08_09-45-11" src="https://github.com/MuiseDestiny/zotero-gpt/assets/133014490/4704df72-b97c-44dc-a24c-3d0b09c123d7">

**Comment by zfb132** [comment]
@Yongzhaooo 只要你设置的`model=gpt-4`，而且收到了返回结果，那么就是4在回答。至于为什么你得到的回答说他自己是3，这是OpenAI官方的问题（官方API接口是比官方网页版要"傻"一些的）。我在官方的API接口测试网页选择`gpt4`模型，进行了相同的问答。
![171012](https://github.com/MuiseDestiny/zotero-gpt/assets/18099238/3c481c7f-8c3a-4c5d-90c8-662568c9bc9e)

你也可以自行测试
https://platform.openai.com/playground?mode=chat&model=gpt-4

你说的"GPT的操作面板上"我不清楚是什么意思

**Comment by Yongzhaooo** [comment]
@zfb132 我说的面板是这个usage统计，不过我现在发现它似乎会延迟一天给统计，所以没看到东西没毛病
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/133014490/3fb8d41e-22ed-4087-8237-bd5a7d84e1cb)
以及这个扣费速度应该确实是GPT4了；感谢你的验证和解答！

**Comment by lihua8848** [comment]
但是他回答说知识更新到2021年，如果是gpt4，他的回答不应该是这样的

**Comment by zfb132** [comment]
> 但是他回答说知识更新到2021年，如果是gpt4，他的回答不应该是这样的

@lihua8848 你需要分清楚网页版GPT与GPT的API的区别。在[GPT的API文档](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo)中指出目前`gpt-4`对应的实际模型是`gpt-4-0613`（知识库截止到2021年9月）。你实际上需要的是`gpt-4-1106-preview`（其知识库截止到2023年4月）。
你可以分别打开 [chat with gpt4](https://platform.openai.com/playground?mode=chat&model=gpt-4)  和 [chat with gpt-4-1106-preview](https://platform.openai.com/playground?mode=chat&model=gpt-4-1106-preview)  进行验证

为了实现你的需求，你可以进行以下操作：  
* 更改模型为`gpt-4-1106-preview`
* 尝试在对话框告诉GPT正确的知识库时间，以尽可能的覆盖插件中可能存在的预先设置的系统提示词（`You are ChatGPT, a large language model trained by OpenAI. Knowledge cutoff: 2021-09`）

例如你可以在对话框输入以下内容（若插件存在系统提示词，可能需要多次执行这句话才能纠正GPT）  
`You are ChatGPT, Knowledge cutoff: 2023-04. 告诉我2022年发生的三件国际大事和具体日期`

![snapshot](https://github.com/MuiseDestiny/zotero-gpt/assets/18099238/4fca534b-3e1f-4871-b746-8ab1641b8559)

**Comment by lihua8848** [comment]
> > 但是他回答说知识更新到2021年，如果是gpt4，他的回答不应该是这样的
> 
> @lihua8848 你需要分清楚网页版GPT与GPT的API的区别。在[GPT的API文档](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo)中指出目前`gpt-4`对应的实际模型是`gpt-4-0613`（知识库截止到2021年9月）。你实际上需要的是`gpt-4-1106-preview`（其知识库截止到2023年4月）。 你可以分别打开 [chat with gpt4](https://platform.openai.com/playground?mode=chat&model=gpt-4) 和 [chat with gpt-4-1106-preview](https://platform.openai.com/playground?mode=chat&model=gpt-4-1106-preview) 进行验证
> 
> 为了实现你的需求，你可以进行以下操作：
> 
> * 更改模型为`gpt-4-1106-preview`
> * 尝试在对话框告诉GPT正确的知识库时间，以尽可能的覆盖插件中可能存在的预先设置的系统提示词（`You are ChatGPT, a large language model trained by OpenAI. Knowledge cutoff: 2021-09`）
> 
> 例如你可以在对话框输入以下内容（若插件存在系统提示词，可能需要多次执行这句话才能纠正GPT） `You are ChatGPT, Knowledge cutoff: 2023-04. 告诉我2022年发生的三件国际大事和具体日期`
> 
> ![snapshot](https://private-user-images.githubusercontent.com/18099238/292709192-4fca534b-3e1f-4871-b746-8ab1641b8559.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0NzkxNTksIm5iZiI6MTcwMzQ3ODg1OSwicGF0aCI6Ii8xODA5OTIzOC8yOTI3MDkxOTItNGZjYTUzNGItM2UxZi00ODcxLWI3NDYtOGFiMTY0MWI4NTU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI1VDA0MzQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyNWEyMWYyYmE2ODgwNjI5NDg3ZTBkMTQwYzUzZTcwYWNkZWMwMTA4M2NhMTkzMTcyMjA3YmEzOWU1NzJhZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Lag6-Qa98RJYX69O71lYQ8mFpXCBlpHZJYAqsRdrXqc)

Thank you!!!
