### ISSUE TITLE
Window closes as soon as it finishes output

### ISSUE THREAD

**Issue by huachuman** [MuiseDestiny/zotero-gpt#266]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**:  Windows 11
- **Zotero version**:  Latest stable
- **Plugin version**:  Latest

### Current Configuration Information

api https://api.openai.com

secretKey sk-…xrOc

model gpt-3.5-turbo

temperature 1.0

### Issue Details

the window closes as soon as GPT finishes responding.

**Comment by lyra-scuti** [comment]
我也会这样

**Comment by zfb132** [comment]
#179
#224

If you are currently opening the GPT window by clicking the icon, please try using the keyboard shortcut `Ctrl + /` to open it instead.
If you are currently opening the GPT window using the keyboard shortcut `Ctrl + /`, please try opening it by clicking the icon instead.

如果你当前正在通过点击图标打开GPT的窗口，请尝试改为使用快捷键`Ctrl+/`来打开
如果你当前正在使用快捷键`Ctrl+/`打开GPT的窗口，请尝试改为使用点击图标打开

**Comment by huachuman** [comment]
Using the shortcut instead of the button seems to work for me.
