### ISSUE TITLE
按Enter无反应。

### ISSUE THREAD

**Issue by baileichao** [MuiseDestiny/zotero-gpt#267]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **windows 11企业版**: 
- **7.0.0-beta.48+0cab24fb8 (64-bit)**: 
- **0.3.2**: 

### 当前配置信息

这个无法出来，因为回车不起作用，输入/命令下面也没有提示。

### 问题详情

打开插件界面，按回车没有反应，必须手动选择下面的AskPDF或其它的按钮才行。
输入/report之类的命令也不会出来什么提示。

**Comment by zfb132** [comment]
尝试卸载并重新安装0.3.2版本
