### ISSUE TITLE
有关界面退出快捷键的问题

### ISSUE THREAD

**Issue by ShengbenBi** [MuiseDestiny/zotero-gpt#268]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

Windows10

### 问题详情

大佬你好，非常喜欢您做的这款gpt插件，让我使用zotero的过程中效率直线提高
但是我在使用过程中遇到一个关于快捷键的问题或者小建议，
在退出界面的时候需要把光标移动到输入框，且输入框中没有内容时摁esc键才能退出
可不可以增加新的快捷键比如ctrl+w关闭窗口，或者增加一个x号用鼠标点，或者移除esc的一些判断（当光标不在输入框或者输入框有内容时可以摁esc直接退出），个人更喜欢ctrl+w的关闭方式，因为跟浏览器中页面关闭思路是一样的。

**Comment by BiShengben** [comment]
大佬你好，非常喜欢您做的这款gpt插件，让我使用zotero的过程中效率直线提高
但是我在使用过程中遇到一个关于快捷键的问题或者小建议，
在退出界面的时候需要把光标移动到输入框，且输入框中没有内容时摁esc键才能退出
可不可以增加新的快捷键比如ctrl+w关闭窗口，或者增加一个x号用鼠标点，或者移除esc的一些判断（当光标不在输入框或者输入框有内容时可以摁esc直接退出），个人更喜欢ctrl+w的关闭方式，因为跟浏览器中页面关闭思路是一样的。

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/432eacca-ec06-46f6-a3c9-e48302753539)

双击这里关闭，或者再次按ctrl+/会隐藏（而非关闭）
