### ISSUE TITLE
有时候chatgpt反应很慢 一直不给结果

### ISSUE THREAD

**Issue by Philip-Cao-9527** [MuiseDestiny/zotero-gpt#27]
使用的是自己的apikey。在官网访问的时候反应速度很快，说明不是科学上网和官方服务器压力过大的问题

**Comment by Philip-Cao-9527** [comment]
另外想问一下，摘要转综述是用的什么代码，逻辑是什么，有时候给出的结果不太准确

**Comment by MuiseDestiny** [comment]
速度慢，我觉得挺快，是慢还是运行出错一直没有结果呢。可能是出错了。所有标签命令，长按你可以修改它的内容。

**Comment by Philip-Cao-9527** [comment]
时快时慢，有时候一直不出结果

**Comment by Guinanren** [comment]
你好，我用的是自己的apikey，在4月1日上午的时候还能运行，从下午开始就无法出结果了。

**Comment by Guinanren** [comment]
> 你好，我用的是自己的apikey，在4月1日上午的时候还能运行，从下午开始就无法出结果了。

我发现用免费调用的apikey时能正常运作，用自己的apikey时无法正常运作。

**Comment by MuiseDestiny** [comment]
> > 你好，我用的是自己的apikey，在4月1日上午的时候还能运行，从下午开始就无法出结果了。
> 
> 我发现用免费调用的apikey时能正常运作，用自己的apikey时无法正常运作。

你的密钥可能有问题，不支持或者被禁

**Comment by Guinanren** [comment]
您好，我已收到您的邮件，我会尽快回复。

**Comment by Guinanren** [comment]
不过奇怪的是，昨天早上用的时候还是一切正常的，我现在从网页登陆GPT也是可以正常使用的。

**Comment by Guinanren** [comment]
> 不过奇怪的是，昨天早上用的时候还是一切正常的，我现在从网页登陆GPT也是可以正常使用的。

我发现我的apikey没有被调用过，还真是我这边的api出问题了

**Comment by Guinanren** [comment]
您好，我已收到您的邮件，我会尽快回复。
