### ISSUE TITLE
[Bug][0.3.2] 插件窗口自动关闭

### ISSUE THREAD

**Issue by ITCJ** [MuiseDestiny/zotero-gpt#272]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**:  7.0.0-beta.51+7c5600913 
- **Plugin version**:  Awesome GPT 0.3.2、Crush Reference 0.6.7.1、Ethereal Style 3.2.8

### 当前配置信息

执行report后自动消失

### 问题详情

1. 执行report后窗口自动关闭
2. 使用askpdf后有一定概率在回答结束时自动关闭窗口
![动画](https://github.com/MuiseDestiny/zotero-gpt/assets/33901467/2ebeb9a5-54a3-4e99-a997-4835e6777437)

### 补充说明

在使用ctrl + / 快捷键打开一次后恢复正常
![动画](https://github.com/MuiseDestiny/zotero-gpt/assets/33901467/690b3aeb-2130-4ca1-a29f-c53006b06d79)

**Comment by MuiseDestiny** [comment]
请更新最新版解决
