### ISSUE TITLE
无法访问全文内容

### ISSUE THREAD

**Issue by opticaa** [MuiseDestiny/zotero-gpt#273]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

问GPT问题，但是它无法访问全文内容只能通过摘要提供回答。

他会说，”很抱歉，我无法直接查看JSON格式的文本中的全文内容。JSON是一种用于存储和传输数据的格式，它不包含完整的论文内容。”  应该怎么解决

**Comment by MuiseDestiny** [comment]
右键长按askpdf 5s。然后重试
