### ISSUE TITLE
可以对标签进行排序吗

### ISSUE THREAD

**Issue by 15153462274** [MuiseDestiny/zotero-gpt#274]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: win
- **Zotero version**: 6.0.30
- **Plugin version**: 0.2.9

### 问题详情

自己新增标签后，总是排到标签栏最前面，可以对标签进行排序吗？

**Comment by zfb132** [comment]
设置标签的`position`的值，值越小越靠前（且保证你的每个标签的`position`的值是唯一的），如下示例将会排在第一个  
```txt
#🤖PaperSummary[position=1][color=#F13433][trigger=/^(本文|这篇文章|论文)/]
<code>
Meet.Zotero.getRelatedText(Meet.Global.input) 
</code>

hello

Reply in <code>Zotero.locale</code>
```

**Comment by MuiseDestiny** [comment]
现在可以长按拖动排序
