### ISSUE TITLE
输入后无响应

### ISSUE THREAD

**Issue by skipskipthree** [MuiseDestiny/zotero-gpt#277]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: win11
- **Zotero version**: zotero 7
- **Plugin version**: 0.50
zotero style为最新版3.3.1.1

### 问题详情

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/33718851/1b662e8d-2abe-484f-a937-be411d37cf30)
输入内容后一直显示如上图所示，窗口没有任何响应

### 补充说明

安装旧版本能顺利使用

**Comment by MuiseDestiny** [comment]
可能是gpt模型导致的，已修复，zotero内自动检查更新即可

**Comment by skipskipthree** [comment]
> 可能是gpt模型导致的，已修复，zotero内自动检查更新即可

更新之后插件可以响应了，但是出现了无法拖动窗口的bug，zotero style为最新版3.3.3.5

**Comment by skipskipthree** [comment]
同时按ctrl+鼠标左键可以移动
