### ISSUE TITLE
与zotero tag这个插件冲突

### ISSUE THREAD

**Issue by YangChunyu1999** [MuiseDestiny/zotero-gpt#28]
如果先安装gpt，tag的动作无法使用，如果先安装tag，gpt整个不能使用

**Comment by MuiseDestiny** [comment]
> 如果先安装gpt，tag的动作无法使用，如果先安装tag，gpt整个不能使用

我后面会调整快捷键～

**Comment by OMGljy** [comment]
大佬，请问为何我在pdf界面shift+tab+/没用呢？反而会有别的应答产生😂不知道是不是快捷键冲突，但是也不知道哪里可以修改

**Comment by MuiseDestiny** [comment]
> 大佬，请问为何我在pdf界面shift+tab+/没用呢？反而会有别的应答产生😂不知道是不是快捷键冲突，但是也不知道哪里可以修改

没用，为什么还有别的应答产生呢。没太听懂

**Comment by OMGljy** [comment]
> 

哦哦可能我没说清楚，就是在pdf界面我按shift+tab+/无法唤出gpt窗口，会跳到左侧标注搜索框，试了很多次都是这样，请教一下是什么问题呢？

**Comment by MuiseDestiny** [comment]
> > 
> 
> 哦哦可能我没说清楚，就是在pdf界面我按shift+tab+/无法唤出gpt窗口，会跳到左侧标注搜索框，试了很多次都是这样，请教一下是什么问题呢？

disable gpt插件再enable再用快捷键唤醒试试

**Comment by OMGljy** [comment]
> 

<img width="1956" alt="image" src="https://user-images.githubusercontent.com/30697056/229347828-8d2a0ffa-f012-4110-bcf7-8e601b0d63dd.png">
尝试了一下，还是不行，您看一下图片上，每次按shift+tab+/都会调到这个窗口里面，无法唤出gpt

**Comment by MuiseDestiny** [comment]
> > 
> 
> <img alt="image" width="1956" src="https://user-images.githubusercontent.com/30697056/229347828-8d2a0ffa-f012-4110-bcf7-8e601b0d63dd.png">
> 
> 尝试了一下，还是不行，您看一下图片上，每次按shift+tab+/都会调到这个窗口里面，无法唤出gpt

选中文字按shift tab /

不选中文字正常shift /

**Comment by OMGljy** [comment]
您好，知道问题在哪里了。如果使用pdf部分GPT功能，至少在mac系统里面，一定要把左侧边栏收起才可以使用按shift+tab+/唤起GPT。谢谢您开发的插件ღ( ´･ᴗ･` )比心

**Comment by MuiseDestiny** [comment]
> 您好，知道问题在哪里了。如果使用pdf部分GPT功能，至少在mac系统里面，一定要把左侧边栏收起才可以使用按shift+tab+/唤起GPT。谢谢您开发的插件ღ( ´･ᴗ･` )比心

其实是这样的，这个事件绑定在了zotero的主界面的document。打开pdf后的document没绑定。而tab作用是让pdf的document失去焦点，让主界面获取按键事件。但是tab本身具有定位到下一个焦点的功能，所以不一定会谁过去焦点。根据你的描述，侧边栏会获取，这样会打断主界面事件触发。总之关于唤醒会优化。

**Comment by OMGljy** [comment]
嗯嗯，原来是这个原因，学习到了hh
