### ISSUE TITLE
ctrl+/无法呼出窗口，点击GPT图标也没有反应

### ISSUE THREAD

**Issue by iwmp-23** [MuiseDestiny/zotero-gpt#280]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**: windows 22H2
- **Zotero version**: 7.0.0-beta.54+6b996d4f9 (64-bit)
- **Plugin version**: 0.5.0

### Issue Details

从zotero6某一版本开始就用不了，我之前以为是zotero版本的问题，
之前尝试过开发者在B站说的创建隔离环境试用zotero7，发现GPT是可以使用的，
但现在我删除了之前创建的环境，整体更新了Zotero7，发现还是无法使用GPT，按快捷键“ctrl+/”或是条目面板上方的“GPT图标”，GPT插件还是没有反应（没有窗口、没有提示），所以应该是我Zotero配置有问题吗？也尝试过卸载后再安装插件，我不会计算机实在不知道哪里有问题……

**Comment by BaiHLiu** [comment]
同样的问题，期待解答。

**Comment by Sheloliv** [comment]
同样的问题 第一次能用 之后再也打不开了

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins

去下载最新插件。

**Comment by Sheloliv** [comment]
二维码已过期 找不到购买渠道


寄件者: Polygon ***@***.***>
日期: 星期二, 2024年1月23日 下午2:27
收件者: MuiseDestiny/zotero-gpt ***@***.***>
副本: Sheloliv ***@***.***>, Comment ***@***.***>
主旨: Re: [MuiseDestiny/zotero-gpt] ctrl+/无法呼出窗口，点击GPT图标也没有反应 (Issue #280)

https://gitee.com/MuiseDestiny/plugins

去下载最新插件。

―
