### ISSUE TITLE
功能建议：在右侧栏添加一个GPT机器人

### ISSUE THREAD

**Issue by linfengtongxue70** [MuiseDestiny/zotero-gpt#285]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: win10
- **Zotero version**: zotero6
- **Plugin version**: 0.2.9

### 当前配置信息

https://api.openai.com
 …
 gpt-3.5-turbo
 1.0

### 问题详情

如题，我希望能在右侧栏添加一个GPT机器人面板，可以在右侧进行对话，并保存对话为该文章的笔记。
应用场景：帮助研0新人了解论文中的专有名词构建知识库。

### 补充说明

![iIn-Operandoi Measurements of Volume Change of C-Si Pouch Cells - Wen 等 - 2017 - Zotero_240123_170607](https://github.com/MuiseDestiny/zotero-gpt/assets/91956234/1ff83f4f-a590-4e20-ab66-5a2015d91ba6)

**Comment by MuiseDestiny** [comment]
新建一个笔记，然后新行空格。

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/49656cb5-558c-45a2-94e4-e8c386838798)

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/051e1a2b-cdf4-4a56-aba3-5f91743c944e)

**Comment by WSQsGithub** [comment]
zotero7有这个功能吗
