### ISSUE TITLE
无法打开gpt窗口, 页面上面没有图标 shift/comand + ?/ 也无法唤出

### ISSUE THREAD

**Issue by Sheloliv** [MuiseDestiny/zotero-gpt#288]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 14.2.1
- **Zotero version**: 7.0.0-beta.56+9edfcba9a
- **Plugin version**: 0.2.9

### 问题详情

安装好的第一天可以用, 之后就怎么都打不开了

**Comment by QYQSDTC** [comment]
升级 beta.56 后打开插件一片空白无法使用
![CleanShot-gvsGphOy@2x](https://github.com/MuiseDestiny/zotero-gpt/assets/15608306/5971db8e-0139-44b7-bf57-1d91d705ae61)

**Comment by reoLantern** [comment]
遇到同样问题，应该是还没有适配新版

**Comment by blankiee1024** [comment]
同样的问题，用了一段时间今天突然消失了。

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-gpt/releases/tag/0.8.0
