### ISSUE TITLE
出现提示额度已超，但我已经一个月未使用GPT插件了

### ISSUE THREAD

**Issue by tong413** [MuiseDestiny/zotero-gpt#295]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

Windows10
zotero 6

### Current Configuration Information

`api` https://api.openai.com
`secretKey` sk-...Rq0F
`model` gpt-3.5-turbo-16k
`temperature` 1.0

### Issue Details

<img width="621" alt="微信图片_20240303005956" src="https://github.com/MuiseDestiny/zotero-gpt/assets/151014779/fed050ac-b514-4734-b164-e7d42a56a36c">
报错详情：
# insufficient_quota
> https://api.openai.com/v1/chat/completions

**insufficient_quota**
You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

### Additional Information

对不起，文科生，烦请大神指点，不胜感激

**Comment by MuiseDestiny** [comment]
相当于手机卡欠费了。你不用也有月租。

GPT 免费密钥领取配置视频教程：https://b23.tv/iPUHXOh

领取地址：https://github.com/chatanywhere/GPT_API_free
