### ISSUE TITLE
askpdf功能无法正常运行

### ISSUE THREAD

**Issue by 314yyhyyh** [MuiseDestiny/zotero-gpt#296]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

OS:win11
Zotero version: 6.0
Plugin version: 0.29

### 问题详情

其他功能均正常，也能够回答问题。就是askpdf无法正常运作。我已经阅读了[#256](https://github.com/MuiseDestiny/zotero-gpt/issues/256#issuecomment-1788439231)，尝试按照其中的内容修改，但还是不能正确运作。

gpt返回的内容如下：
很抱歉，仍旧无法从您提供的上下文信息中获取到具体的查询内容。在占位符 ${Meet.Global.input} 中没有实际的问题或查询语句。没有这个信息，我无法撰写一个回答。
如果您有具体的问题或需要寻找相关文献，请提供明确的查询内容。一旦我了解了您的查询需求，无论是回答问题还是提供与查询相关的文献信息，我都将竭尽所能地协助您。
为了更好地帮助您，请将 ${Meet.Global.input} 替换成您的具体问题。

### 补充说明

目前的标签内容如下
#🪐AskPDF[position=10][color=#0EA293][trigger=/^(本文|这篇文章|论文)/]
You are a helpful assistant. Context information is below.
${
Meet.Global.views.messages=[];
Meet.Zotero.getRelatedText(Meet.Global.input)
}
Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information.

Answer the question: $\{Meet.Global.input\}

Reply in zh-cn

**Comment by gwx06** [comment]
同样问题  
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/46440741/3643591c-80bb-4059-834d-584d55323d52)

**Comment by ENDlezZenith** [comment]
同

**Comment by MuiseDestiny** [comment]
右键长按askpdf 5s。然后重试

**Comment by 314yyhyyh** [comment]
> 右键长按askpdf 5s。然后重试

是右键长按这个tag的图标吗？尝试了，但是没有效果。

**Comment by moyinQAQ** [comment]
> 右键长按askpdf 5s。然后重试

长按后无反应

**Comment by Sumsky21** [comment]
没反应+1
zotero版本：6.0.36
插件版本：0.2.9
已经尝试 #256 和本issue的解决方案，均无效。
