### ISSUE TITLE
[UI/UX]: 0.2.9版本有两个Releases应该如何选择

### ISSUE THREAD

**Issue by ENDlezZenith** [MuiseDestiny/zotero-gpt#297]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

OS: Windows 10 22H2
Zotero Version: 6.0.30
Plugin Version: 0.2.9

### 问题详情

0.2.9版本有两个Releases，分别是zotero-gpt.xpi和zotero-gpt-129.xpi，应该如何选择？请问是不是可以标注一下区别，以免导致我一样的困惑，谢谢。顺便zotero-gpt-129.xpi有一个小问题，左上角的图标不显示，但是Ctrl+/可以正常唤醒。

**Comment by MuiseDestiny** [comment]
选zotero-gpt-129.xpi，快捷键唤醒即可。

**Comment by ENDlezZenith** [comment]
好的感谢
