### ISSUE TITLE
如何替换embbding模型？

### ISSUE THREAD

**Issue by Donnie-Liang** [MuiseDestiny/zotero-gpt#303]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

OPENAI已经出了text-embedding-3-small 和 text-embedding-3-large，价格比老的text-embedding-ada-002模型更为便宜，如何修改将embedding模型替换为新的模型？

**Comment by a90091343** [comment]
同样的需求+1，5分之1的价格，更好的性能，对azure Openai学生用户来说实在是太友好了

**Comment by ouening** [comment]
同样的需求，请求作者加入自定义embedding和llm模型的功能，比如如何ollama本地部署的模型进行推理

**Comment by lazyracket** [comment]
@ouening  刚在本地电脑使用 LM Studio 配置`Qwen1.5` + `mxbai-embed-large`两个模型，启动服务后，重启 zotero-gpt：
`/secretKey` 默认 `lm-studio`
`/model` 设置 `Publisher/Repository` （在`models`目录下新建，只存放上述两个模型）
`/api` 默认 `http://localhost:1234`  

LM Studio 兼容 OpenAI 接口 并且支持嵌入。亲测有效，就是风扇太累了...

---
macOS 14.4.1
Zotero 6.0.37
zotero-gpt 0.3.0

**Comment by ouening** [comment]
试了一下lm studio只能使用localhost，无法在局域网使用，我之前的测试使用ollama、llamafile等部署，然后用llamaindex做调用，作者可否支持这种？

**Comment by wdoo02** [comment]
我试着改了一下，成功实现了 text-model-ada-002 和 kimichat 混搭
各位试试别的 embedding 模型？我在实现里开放了 embedding 的模型参数设置
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/43543597/b0919be1-beff-4e87-be1f-f8b27d8904c1)

https://github.com/wdoo02/zotero-gpt/releases/tag/0.2.8.1

**Comment by MuiseDestiny** [comment]
https://github.com/MuiseDestiny/zotero-gpt/releases/tag/0.8.4

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/d77d227c-f16a-411d-b623-109fd394d93e)

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/cf4477f5-5b16-4ff5-93d5-b17eb162b5cb)


支持的模型包括Ollama的："mxbai-embed-large", "nomic-embed-text", "all-minilm"，

Openai的所有。

**Comment by lazyracket** [comment]
@MuiseDestiny 请问 [0.8.4](https://github.com/MuiseDestiny/zotero-gpt/releases/tag/0.8.4) 是不是只能安装在 Zotero **7** ? 新功能后续会支持 Zotero **6** 么 ...

将来 Ollama 实现支持 OpenAI 的 `/v1/embeddings` 应该会解决很多问题。
