### ISSUE TITLE
GPT4设置问题

### ISSUE THREAD

**Issue by Sober-J** [MuiseDestiny/zotero-gpt#310]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: MacOS Ventura 13.6.6
- **Zotero version**: 6.0.37
- **Plugin version**: 0.2.9

### 当前配置信息

api https://api.openai.com
secretKey sk-…MzEX
model gpt-4
temperature 1.0

### 问题详情

调整好配置后仍然显示model_not_found
已经确保gpt-4已开通且生成了API KEY
<img width="533" alt="Screenshot 2024-04-06 at 18 29 58" src="https://github.com/MuiseDestiny/zotero-gpt/assets/52737440/dd123e03-0692-48fd-a79d-03e288d771b8">

**Comment by ClairCccc** [comment]
我也是这样 根本用不了

**Comment by MuiseDestiny** [comment]
模型不存在是openai服务器报错，与插件无关
