### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by wefuiwheoi** [MuiseDestiny/zotero-gpt#312]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 23h2
- **Zotero version**: 7.0.0-beta.72+128a540af (64-bit)
- **Plugin version**: 0.6.0

### 问题详情

就zotero昨天更新之后就用不了了，没有图标，快捷键也不行，插件重装也不行。

**Comment by LHLdragon579** [comment]
我也是，请问什么情况

**Comment by wefuiwheoi** [comment]
> 我也是，请问什么情况

不知道，应该是更新的问题，更新给我茉莉花插件都弄得用不了了，我用回zotero6版本了，这次更新问题太大了，界面还有中英文夹杂的，唉

**Comment by wefuiwheoi** [comment]
已修复，可以正常使用

**Comment by SuperMaxine** [comment]
> 已修复，可以正常使用

请问是怎么修复的？更新了zotero吗？我在7.0.0-beta.72+128a540af (64-bit)这个版本直接把所有软件中的网络操作（插件、webdav等）搞崩了，自动更新都挂了
