### ISSUE TITLE
Library 界面不加载

### ISSUE THREAD

**Issue by FranklinXuNorth** [MuiseDestiny/zotero-gpt#313]
### 这个问题是否已有issue

- [x] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows10 
- **Zotero version**:  6.0.20
- **Plugin version**:  0.2.9

### 当前配置信息

api https://api.openai.com
secretKey sk-…0okH
model gpt-4-turbo-2024-04-09
temperature 1.0

### 问题详情

如图，Library显示一片空白
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/144621512/0519cc38-6e81-4046-aad0-778a0c5b37f7)

但文献一切正常
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/144621512/37bea884-8546-4f18-a39a-90920a3998ed)

已确认是 GPT 插件的问题，因为禁用后问题就消失了。

### 补充说明

稳定复现，非常稳定复现。而且仅限library界面

**Comment by MuiseDestiny** [comment]
不再更新支持zo 6的插件。请回退版本试试。
