### ISSUE TITLE
Pro 版本的GPT对话框中每次开启都会复制一遍之前的对话

### ISSUE THREAD

**Issue by ZIV-LY** [MuiseDestiny/zotero-gpt#314]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows11 23H2
- **Zotero version**: 7.0.0
- **Plugin version**: 0.8.0

### 问题详情

Pro版本的GPT的对话框中，文章在每次关闭再打开的时候，都会把历史对话记录全都复制一遍。

### 补充说明

稳定复现

**Comment by MuiseDestiny** [comment]
最新版问题若还存在，请去https://gitee.com/MuiseDestiny/plugins反馈
