### ISSUE TITLE
求问your secretKEY is not configured怎么解决

### ISSUE THREAD

**Issue by FabiolaSecond** [MuiseDestiny/zotero-gpt#315]
### 这个问题是否已有issue

- [ ] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

![1713168503841](https://github.com/MuiseDestiny/zotero-gpt/assets/152482226/a210b7b7-56b9-4765-b28a-713997cd048c)

**Comment by Bellaang** [comment]
我也是这样的问题，请问您解决了吗

**Comment by AWSHIBASHI** [comment]
同问

**Comment by Bellaang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by AWSHIBASHI** [comment]
在设置里配置一下embeddings，选择api，model，输入key，配置完就可以正常使用
