### ISSUE TITLE
askpdf报错

### ISSUE THREAD

**Issue by mitu752** [MuiseDestiny/zotero-gpt#321]
### 这个问题是否已有issue

- [x] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11
- **Zotero version**: 7.0.0-beta.77+adaa61f2c (64-bit)
- **Plugin version**: 0.8.4

### 当前配置信息

api https://api.xxxx.xyz
secretKey sk-…6b08
model gpt-3.5-turbo
temperature 1.0

### 问题详情

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/59833868/4aa9065b-73f5-40e8-bd09-33591e1cc3ec)
让gpt总结时报错，回答：为了给出全面的总结，我需要更多关于你提到的内容的信息。你可以提供更多背景信息吗？
gptapi后台看了也没调用text-embedding-ada-002

### 补充说明

稳定复现，所有pdf和paper都同样

**Comment by mitu752** [comment]
这是askpdftag代码：
#🪐AskPDF[color=#0EA293][trigger=/^(本文|这篇文章|论文)/]
You are a helpful assistant. Context information is below.
${
Meet.Zotero.getRelatedText(Meet.Global.input || Meet.Global.views.messages[0].content)
}$
Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information.

Answer the question: ${Meet.Global.input || Meet.Global.views.messages[0].content}$

Reply in zh-CN.

按issue右键标签5s仍得不到解决

**Comment by MuiseDestiny** [comment]
zo内检查更新。0.8.7

**Comment by mitu752** [comment]
最新版不是0.8.4吗
[0.8.4: 自定义embeddings模型](https://github.com/MuiseDestiny/zotero-gpt/releases/tag/0.8.4)
zotero版本也是最新版本

**Comment by mitu752** [comment]
> zo内检查更新。0.8.7

没懂这句话的意思，能解释下吗 佬
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/59833868/6bfdf8e0-334e-443d-a3ee-f8fa726f0999)

**Comment by MuiseDestiny** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/51939531/f5588e46-dac0-434b-a75f-b126814c71e0)
更新插件，不是zo软件哦

**Comment by mitu752** [comment]
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/59833868/4e71d205-c53a-4fb8-b07d-a9527f8bcec2)
但是我这个一直是开着的啊 佬

> ![image](https://private-user-images.githubusercontent.com/51939531/328125931-f5588e46-dac0-434b-a75f-b126814c71e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODYxNDEsIm5iZiI6MTcxNDk4NTg0MSwicGF0aCI6Ii81MTkzOTUzMS8zMjgxMjU5MzEtZjU1ODhlNDYtZGFjMC00MzRiLWE3NWYtYjEyNjgxNGM3MWUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA4NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkMjczYjhiMjM4NGI2NTBhM2E3YzJhNzdmMGYyNDFmYjEwYzMzNDYwZGVmOGEzNGUxNTg4OWMwOTMyM2E2OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UVJW3-syY8OyfOfaN4ghOLVThe2buCHte_kMBwjHZV8) 更新插件，不是zo软件哦
