### ISSUE TITLE
不能读pdf的反馈

### ISSUE THREAD

**Issue by xqinshan** [MuiseDestiny/zotero-gpt#325]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 
- **Zotero version7.0.0-77: 
- **Plugin version**: 030和084

### 当前配置信息

 #🪐AskPDF2[color=#0EA293][trigger=/^(本文|这篇文章|论文)/]
You are a helpful assistant. Context information is below.

${
Meet.Global.views.messages = [];
Meet.Zotero.getRelatedText(Meet.Global.input)
}

Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information.

Answer the question: 
${Meet.Global.input}
用中文回答

也试了其他code，情况差不多
<code>
Meet.Zotero.getPDFSelection() ||
Meet.Global.views.messages[0].content
</code>

$\{
Meet.Global.views.messages = [];
Meet.Zotero.getRelatedText(Meet.Global.input)
\}

### 问题详情

zotero是7.0版的，试了几个版本的gpt插件，比如030版，点击askpdf会显示读pdf，页数(比如10/10，7/7)正确，表示可能真的在读pdf，然后就不动了。  最新版084版，打开PDF文件再打开插件，输入"本文主要内容"等，点击askPDF，一般显示："我无法生成答案，因为我缺乏外部信息的访问权限。"  （还看到过瞎回复的，可能是较低一些版本）

如果粘贴一段文字，再点击askpdf，会有正确的内容输出。总结就是
1）低版本030插件假死在readpdf状态，2）高版本084似乎没读pdf，提示无访问权限。

看过这里大部分相关讨论，好像都不行，另外对于zotero6是不是已经解决了这问题？

### 补充说明

稳定复现，多个pdf都类似。

**Comment by xqinshan** [comment]
看过issus中的相关内容，解决不了。另外zotero6是不是已经解决了这个问题？

**Comment by dianzuan** [comment]
我也有类似问题，详细说明如下：
Zotero版本：7.0.0beta
zotero-gpt版本：0.8.2（0.8.4问题一致，尝试降到0.8.2未解决问题）
![2024-05-13_12-33_1](https://github.com/MuiseDestiny/zotero-gpt/assets/90224130/8b7cdda7-1793-4f0d-8be8-1e6823c05c7e)
![2024-05-13_12-33](https://github.com/MuiseDestiny/zotero-gpt/assets/90224130/99c98a74-5832-4026-9687-55c381776b65)
使用的模型：
![2024-05-13_12-36](https://github.com/MuiseDestiny/zotero-gpt/assets/90224130/375ce0bd-3958-416b-97c5-168535adb417)
b站评论处也有许多提及这个问题的留言

**Comment by dianzuan** [comment]
@xqinshan 问题解决了 在zotero插件中的zotero-gpt 检查插件更新至0.8.7 重启gpt就解决了假读的问题

**Comment by gzqx** [comment]
我更新到了0.8.8依然出现这个问题。

似乎是Meet.Zotero.getRelatedText()没有被处理，直接传了这个代码给gpt

**Comment by xqinshan** [comment]
> @xqinshan 问题解决了 在zotero插件中的zotero-gpt 检查插件更新至0.8.7 重启gpt就解决了假读的问题

在哪看到新版的，只有0.8.4啊！

**Comment by jsrdcht** [comment]
我这里也和 @gzqx 一样，且zotero和插件都更新到了zotero7的最新版。

API没有被正确调用，平台是M1 MAC
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/22300065/db004a7e-16a6-466e-b53c-4f8d7ff705f6)

**Comment by MuiseDestiny** [comment]
请升级插件，zo内检查更新。然后重启即可修复。或手动下载：https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-gpt.xpi

**Comment by gzqx** [comment]
更新到了0.9.0，或卸载后从上述连接下载安装，AskPDF均依然报同样错误

![Screenshot_20240612_220318](https://github.com/MuiseDestiny/zotero-gpt/assets/24262751/38163435-b537-46de-b169-85d984ba8d25)

**Comment by MuiseDestiny** [comment]
> 更新到了0.9.0，或卸载后从上述连接下载安装，AskPDF均依然报同样错误
> 
> ![Screenshot_20240612_220318](https://private-user-images.githubusercontent.com/24262751/339002397-38163435-b537-46de-b169-85d984ba8d25.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDE5MzEsIm5iZiI6MTcxODIwMTYzMSwicGF0aCI6Ii8yNDI2Mjc1MS8zMzkwMDIzOTctMzgxNjM0MzUtYjUzNy00NmRlLWIxNjktODVkOTg0YmE4ZDI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE0MTM1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiNmM4NmQ2NjQ3NGEzNDVkZDg3YzQxZDczZGJhZDllYTZlY2EwNjIxYzExNTVlYzcxZjk2ODEwOGEzODcyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7LuI-RqDsDZ8afVtwMlHAB5BW5npFxK7VFwvfapWbQ)

**右**键长按askpdf 5s，然后重试

**Comment by gzqx** [comment]
> **右**键长按askpdf 5s，然后重试

依然如此，看下图似乎是parser卡住了
![Screenshot_20240612_221620](https://github.com/MuiseDestiny/zotero-gpt/assets/24262751/58618f71-5f0f-42a5-bb8e-92d1bc13fedb)

**Comment by MuiseDestiny** [comment]
> > **右**键长按askpdf 5s，然后重试
> 
> 依然如此，看下图似乎是parser卡住了 ![Screenshot_20240612_221620](https://private-user-images.githubusercontent.com/24262751/339007184-58618f71-5f0f-42a5-bb8e-92d1bc13fedb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyMDI5ODEsIm5iZiI6MTcxODIwMjY4MSwicGF0aCI6Ii8yNDI2Mjc1MS8zMzkwMDcxODQtNTg2MThmNzEtNWYwZi00MmE1LWJiOGUtOTJkMWJjMTNmZWRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDE0MzEyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmYjIyYTBiZTJiOTE0NTQ0OThmOWE3MmRmYjJjMWQ0NTk3MDdjMTRlMGMyOTRkOWNmN2I4NTQzZTNlODM5MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dEup0bmWajjNFfU43kz1rFNWS9wumYw8RVjsgt8FGtw)

zoytero软件不是最新吧

**Comment by gzqx** [comment]
更新到最新以后，确实不显示这个对话框，变成了卡死不出结果。 （用Selection提问能正常回复）

**Comment by Gibo-Chun** [comment]
> 更新到最新以后，确实不显示这个对话框，变成了卡死不出结果。 （用Selection提问能正常回复）
我也遇到了一样的问题，想请教一下现在有好的解决方法吗/(ㄒoㄒ)/~~
