### ISSUE TITLE
嵌入 prompt 的代码不执行

### ISSUE THREAD

**Issue by sheldon123z** [MuiseDestiny/zotero-gpt#329]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 14.4.1
- **Zotero version**: 7.0.0-beta.79+95d5a5417
- **Plugin version**: 8.04

### 当前配置信息

```
api https://api.deepseek.com
secretKey sk-…
model deepseek-chat
temperature 1.0
```

### 问题详情

输出的是对 prompt 的解释而不是选中的 pdf，代码没有被执行，所有的命令都试了，都不执行代码，而是直接将代码打包成文字发给大模型了

<img width="1141" alt="image" src="https://github.com/MuiseDestiny/zotero-gpt/assets/42455304/34da9b57-c3ef-482e-9e65-e60f9209f27a"> 

### 补充说明

估计可以稳定复现

**Comment by MuiseDestiny** [comment]
**右**键标签Selection 5s，即可重置内部代码。然后就可以了。

**Comment by Yam0214** [comment]
> **右**键标签Selection 5s，即可重置内部代码。然后就可以了。

同样的问题。并且我右键长按5s，标签就被删除了
