### ISSUE TITLE
[BUG]  this[][][]is not a function。 Ask pdf 错误

### ISSUE THREAD

**Issue by wwjCMP** [MuiseDestiny/zotero-gpt#330]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  windows 11
- **Zotero version**: 7.0.0-beta.73+398454f85 (64-bit)
- **Plugin version**: 0.8.9

### 问题详情

软件和插件更新到最新版还是这样

![1716261718954](https://github.com/MuiseDestiny/zotero-gpt/assets/32979859/0b667a14-75cd-4d43-aeb5-70125a6ab186)

### 补充说明

稳定复现

**Comment by wwjCMP** [comment]
看了一下，ollama 服务那边完全没有接收到嵌入模型请求

**Comment by MuiseDestiny** [comment]
更新zo软件
