### ISSUE TITLE
[BUG] 0x433484 [_0x14054c(...)] is undefined

### ISSUE THREAD

**Issue by wwjCMP** [MuiseDestiny/zotero-gpt#332]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11
- **Zotero version**: 7.0.0-beta.73+398454f85 (64-bit)
- **Plugin version**: 0.9

### 当前配置信息

api http://192.168.101.19:11434
secretKey sk...sk
model llama3
temperature
0.4

### 问题详情

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/32979859/1aee6e85-9d25-4665-9efc-0001cfa6a192)

### 补充说明

稳定复现

**Comment by wwjCMP** [comment]
#🪐AskPDF[color=#0EA293][trigger=/^(本文|这篇文章|论文)/]
You are a helpful assistant. Context information is below.
${
Meet.Zotero.getRelatedText(Meet.Global.input || Meet.Global.views.messages[0].content)
}$
Using the provided context information, write a comprehensive reply to the given query. Make sure to cite results using [number] notation after the reference. If the provided context information refer to multiple subjects with the same name, write separate answers for each subject. Use prior knowledge only if the given context didn't provide enough information.

Answer the question: ${Meet.Global.input || Meet.Global.views.messages[0].content}$

Reply in zh-CN.

**Comment by MuiseDestiny** [comment]
请更新zo到最新7.0.0-beta.84+71f83c0a3
