### ISSUE TITLE
看起来不能执行prompt中的函数调用

### ISSUE THREAD

**Issue by Yam0214** [MuiseDestiny/zotero-gpt#335]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: window 11
- **Zotero version**:  7.0.0-beta.87+f59a4da7f (64-bit)
- **Plugin version**: 0.8.4

### 当前配置信息

api https://localhost:port
secret Key sk-******
model glm-4
temperature 1.0

### 问题详情

```
#解释一下[color=#F1603E][trigger=解释一下]
${Meet.Zotero.getItemField()}

解释一下
```

![image](https://github.com/MuiseDestiny/zotero-gpt/assets/40912707/ca338e26-860e-4761-a375-e07051c6a08d)
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/40912707/679d519c-5d7e-4df3-b6c6-37a4dff0d74b)

### 补充说明

- 已阅读 issues，尝试了其中提供的解决方案，无效
    - 确保输入框中有文本，非空白
    - 已更新插件至最新版本（0.8.4 pre-release）
    - 已修改标签内容，包括`${function}$`和`$\{function\}$`两种形式，但似乎代码块并未执行

**Comment by MuiseDestiny** [comment]
使用`${}$`包裹代码 或`<code></code>`

**Comment by Yam0214** [comment]
> 使用`${}$`包裹代码 或`<code></code>`


- 已使用更新后的插件 version= 0.9.1
- 用`<code></code>`包裹代码
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/40912707/51c9551c-b4db-41cc-afc5-0d4e86fe93dc)
- 用`${}$`包裹代码
![image](https://github.com/MuiseDestiny/zotero-gpt/assets/40912707/ad2e7603-b48b-40bd-8c69-4eff0ad191f1)
