### ISSUE TITLE
开发者您好，闲鱼上有人再售卖您Zotero GPT Pro 插件的破解版，请注意防范 

### ISSUE THREAD

**Issue by WANGZFOF** [MuiseDestiny/zotero-gpt#336]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 22H2
- **Zotero version**: 6.0.23
- **Plugin version**: 0.2.3

### 问题详情

售卖破解盗版Zotero GPT Pro 的闲鱼用户，名为“九俉”，您可以去看下，请做好相关的防护措施

**Comment by MuiseDestiny** [comment]
好的，感谢告知！

**Comment by Haolius** [comment]
jianrne
