### ISSUE TITLE
Zotero 7.0.0-beta.91+3c6625f3c功能不工作

### ISSUE THREAD

**Issue by FelixHuoEZ** [MuiseDestiny/zotero-gpt#340]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Win 10
- **Zotero version**:  7.0.0-beta.91+3c6625f3c
- **Plugin version**:  0.8.4

### 问题详情

Zotero 7.0.0-beta.91+3c6625f3c 中功能不工作。

**Comment by MuiseDestiny** [comment]
最新0.9.1 请在zo内部检查更新

**Comment by FelixHuoEZ** [comment]
Not work either, but my Zotero is updated to 7.0.0-beta.92+d5bb667fb.
