### ISSUE TITLE
API was stolen, 10$ !!!!!!!!!!

### ISSUE THREAD

**Issue by ZJLXXXX** [MuiseDestiny/zotero-gpt#351]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: 
- **Zotero version**: 
- **Plugin version**: 

### 问题详情

API was stolen, 10$ !!!!!!!!!!

### 补充说明

Since I used this plugin two days ago, my API usage has skyrocketed, and I was playing games yesterday and didn't use the API at all.
If it's not your official problem. Please investigate it carefully!!! I suspect that the developers of Zotero Chinese have stolen my API.

**Comment by MuiseDestiny** [comment]
请关闭插件 自行检查在哪里调用流失的额度。没人偷你额度。也请你尽快删除你配置的密钥，避免进一步的损失。
