### ISSUE TITLE
首选项中插件设置丢失

### ISSUE THREAD

**Issue by SepineTam** [MuiseDestiny/zotero-gpt#352]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: macOS 15.0beta
- **Zotero version**: 7.0.1
- **Plugin version**: 0.8.4

### 当前配置信息

`api` https://api.deepseek.com
`secreKey` sk-...e846
`model` deepseek-chat
`temperature` 1.0

### 问题详情

# 首选项中丢失GUI配置界面。
## 现象
当完成install后在首选项中没有该插件的选项卡
**如图所示**
<img width="800" alt="image" src="https://github.com/user-attachments/assets/9f0e1f12-9cd0-40ce-ad47-ed14cb644437">

但可通过快捷键 `command + /` 打开命令行使用命令。

### 补充说明

重启zotero和计算机均不改变。同时尝试过重新安装zotero和插件均未奏效。

**Comment by MuiseDestiny** [comment]
https://gitee.com/MuiseDestiny/plugins/blob/master/zotero-gpt.xpi
