### ISSUE TITLE
api路径不支持自定义，默认/v1/chat/completions

### ISSUE THREAD

**Issue by cccssssss123** [MuiseDestiny/zotero-gpt#357]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: win11
- **Zotero version**: 7
- **Plugin version**: 1.2.0

### 问题详情

![image](https://github.com/user-attachments/assets/0703306b-15a9-4034-a759-7c37870857eb)
目前无法自定义api后缀，默认是v1/chat/completions，这个功能能否在下个版本加一下，谢谢
源代码可能为：src\modules\Meet\OpenAI.ts 中的202行

**Comment by chchz** [comment]
支持去除默认的后缀，zhipu他们家的后缀就不是这个

**Comment by BarrryYoung** [comment]
> 支持去除默认的后缀，zhipu他们家的后缀就不是这个

man，怎么在去除呀 没找到这个设置

**Comment by zhao-leo** [comment]
> 支持去除默认的后缀，zhipu他们家的后缀就不是这个

同问

**Comment by X-Bruce-Y** [comment]
同求，关注

**Comment by seifer08ms** [comment]
现在已经通过Full API 和Base API来切换，支持了这个特性，可以关闭了
