### ISSUE TITLE
mac系统下的唤醒快捷键是哪个？

### ISSUE THREAD

**Issue by bhnan** [MuiseDestiny/zotero-gpt#362]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: mac
- **Zotero version**: 7
- **Plugin version**: 1.20

### 问题详情

如题，mac系统下，快捷键无法触发。

**Comment by SawyerAllen** [comment]
我也是，你的可以使用了吗？我怀疑Mac版本Zotero7的插件根本无法使用

**Comment by MuiseDestiny** [comment]
无论win/mac都有按钮，可以点击打开。Mac：control+/
![image](https://github.com/user-attachments/assets/a3598ac0-94f4-40c2-8483-87412424e403)

**Comment by SawyerAllen** [comment]
<img width="1079" alt="image" src="https://github.com/user-attachments/assets/c3274772-727e-4148-9fb7-91ba77156584">
Mac上的Zotero7，安装了插件，但是没有显示插件的图标，按command+/或者是control+/都没有反应，之前用zotero6时是可以正常使用的，😭
