### ISSUE TITLE
Reporting virus

### ISSUE THREAD

**Issue by Ceazy-Gentleman** [MuiseDestiny/zotero-gpt#367]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: Windows11 22H2
- **Zotero version**: 7.0.3
- **Plugin version**: 1.2

### 问题详情

Reporing there are  virus in the plugin when  I downloaded the plugin of version 1.2.

### 补充说明

可以复现

**Comment by MuiseDestiny** [comment]
Please ignore the reminder
