### ISSUE TITLE
怎么改成英文

### ISSUE THREAD

**Issue by leiwu0227** [MuiseDestiny/zotero-gpt#37]
大神你好，怎么把显示改成英文啊，我看你的介绍里都是英文的，不知道应该在哪里设置。因为平时读很多英文文献，翻成中文不太习惯。谢谢！！！

**Comment by MuiseDestiny** [comment]
长按标签

**Comment by leiwu0227** [comment]
谢谢，明白，但是我长按以后，修改标签然后按enter 命令不执行，一直不停换行，是需要按其他什么的吗

**Comment by leiwu0227** [comment]
比如我在框里打了下面的程序，但是按回车执行不了，不停的换行。

#Summarize[pos=0]
Summarize the following text：
```js
const ztoolkit = Zotero.ZoteroGPT.data.ztoolkit
let getSelection = () => {
    return ztoolkit.Reader.getSelectedText(
 Zotero.Reader.getByTabID(Zotero_Tabs.selectedID)
    );
}
console.log(getSelection())
getSelection()

```

**Comment by MuiseDestiny** [comment]
ctrl s

最新版有一个引导

ctrl r是执行

**Comment by MuiseDestiny** [comment]
Type #label_name[color=#eee][position=1] and Enter to edit a lable. Save with Ctrl + S. Save and Run with Ctrl + R.

readme也有

**Comment by leiwu0227** [comment]
搞定，谢谢🙏！

**Comment by chloejooo123** [comment]
我按了ctrl s ctrl r，第一次什么变化都没有，第二次下面一直在load...

**Comment by chloejooo123** [comment]
哦哦好了看到下面有新标签了，请问怎么删除中文的标签啊

**Comment by MuiseDestiny** [comment]
右键长按标签
