### ISSUE TITLE
Zotero GPT插件之间的兼容性问题

### ISSUE THREAD

**Issue by luohao0925** [MuiseDestiny/zotero-gpt#374]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**:  Windows11 23H2
- **Zotero version**: 7.0.5
- **Plugin version**: 1.2.0

### 当前配置信息

无

### 问题详情

Zotero安装GPT插件后，可以正常显示及使用，但继续安装其余插件，如translate等，GPT插件就无法正常使用了，也无法使用ctrl + / 呼出

<img width="576" alt="image" src="https://github.com/user-attachments/assets/0a10cd58-e6d7-47c5-af1b-0ec7cc75016c">

<img width="567" alt="image" src="https://github.com/user-attachments/assets/ddaeab05-ecc9-4c54-854c-8b1737e799f7">

是否是兼容性问题呢？

### 补充说明

可以稳定复现，我在不同的windows版本以及linux版本上均存在同一问题

**Comment by YouJiacheng** [comment]
我只有Zotero GPT (Awesome GPT)和Zotero PDF Translate(Translate for Zotero)也冲突。

**Comment by YouJiacheng** [comment]
在Zotero Plugins Manager里更新插件即可解决。
https://github.com/MuiseDestiny/zotero-gpt/issues/368#issuecomment-2363548630

**Comment by luohao0925** [comment]
感谢，可以了！
