### ISSUE TITLE
AskPDF模块用不了

### ISSUE THREAD

**Issue by vincnttt** [MuiseDestiny/zotero-gpt#375]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**: Windows 11
- **Zotero version**: 7.0.5 (64-bit)
- **Plugin version**: 1.2.0

### Current Configuration Information

`api` https://api.turboai.one
`secretKey` sk-…Ce50
`model` gpt-4o-mini
`temperature` 1.0

### Issue Details

AskPDF模块没给结果，但在API后台显示调用了... API测试显示正常...
**PS**: 前两周能用，这几天不知道突然用不了了

### Additional Information

AskPDF模块没给结果，但在API后台显示调用了：
![image](https://github.com/user-attachments/assets/e5a42a88-7651-44a6-976f-2acb0517595b)
一般情况下 (如：网卡) 下面输出框会显示闪烁，但这没有...

API测试结果：
![image](https://github.com/user-attachments/assets/2825d80c-e7b0-4393-b0af-cdb4411ffa2c)

**Comment by MuiseDestiny** [comment]
可否录屏，目前信息太少

**Comment by vincnttt** [comment]
以下视频可以看一下，发不了很长的视频，已经等了十几秒没什么变化：
https://github.com/user-attachments/assets/66072866-2168-4484-aa55-37c029087c1e

视频里ctrl+enter后，没任何输出而且右下角有提示（execTask#AskPDF）如下：
![image](https://github.com/user-attachments/assets/faaa2a07-15ed-41d2-a48b-29f3ae88f401)

**Comment by vincnttt** [comment]
> 可否录屏，目前信息太少

已经重装插件，版本是1.2.3，还是不行

**Comment by vincnttt** [comment]
已解决，ctrl+r 执行命令，一直搞错以为是 ctrl+enter😅
