### ISSUE TITLE
启动后报错：  HTTP POST https://api.siliconflow.cn/v1/v1/chat/completions failed with status code 400: {“code”:20012,“message”:“Model does not exist. Please check it carefully.”,“data”:null} 如果是网络问题，建议优化网络，比如打开/切换代理等。      确定API填写正确  

### ISSUE THREAD

**Issue by 2024-cmyk** [MuiseDestiny/zotero-gpt#377]
### Has this issue been reported before?

- [X] I confirm that there is no existing issue, and I have read the **FAQ**

### Operating Environment

- **OS**: Windows11
- **Zotero version**: Zotero 7
- **Plugin version**: 1.2.0

### Current Configuration Information

api https://api.siliconflow.cn/v1
secretKey sk-…hwwa
model Qwen2.5-7B-Instruct
temperature 0.9

### Issue Details

![image](https://github.com/user-attachments/assets/5a77f695-f440-4f2c-b697-1d57c23f6bc5)
![image](https://github.com/user-attachments/assets/740b9f80-8592-4e79-9e18-ab1dc6c299c4)

### Additional Information

![image](https://github.com/user-attachments/assets/d4003db6-1241-444d-b0a2-68c795539a01)

**Comment by fun1024** [comment]
同样的问题，请问解决了吗？

**Comment by dempsey-wen** [comment]
去掉一个/v1试试

**Comment by 2024-cmyk** [comment]
> 去掉一个/v1试试

还是不行
![Uploading image.png…]()

**Comment by Steve0ne** [comment]
我目前卸载了山茶花后，这个插件就恢复正常了

**Comment by Sheldongg** [comment]
啥玩意软件 全是bug

**Comment by MuiseDestiny** [comment]
提示模型不存在，请检查模型，包括大小写 是否拼错。

**Comment by 2024-cmyk** [comment]
> 提示模型不存在，请检查模型，包括大小写 是否拼错。

好的谢谢哈，可以啦

**Comment by Dustella** [comment]
我尝试不使用 BaseURL，使用 FullAPI 并且填写成 `https://[baseurl]/v1/chat/completions` 之后生效了。

看上去好像现在插件会尝试请求 `/v1/completion` 这个借口，但是我看到别的很多应用用的是 `/v1/chat/completion`

希望作者可以注意到这个问题 @MuiseDestiny

**Comment by MuiseDestiny** [comment]
感谢提醒，手滑写错了，最新版已经改正。

**Comment by jhuang2023** [comment]
下载了Dec 04 2024 的.xpi 但依然有这个问题。请问我如何可以自己修正

**Comment by ZhongQiyu** [comment]
> 下载了Dec 04 2024 的.xpi 但依然有这个问题。请问我如何可以自己修正

.xpi是zotero用的吧，还有如果是api要把v1/completions加上？
