### ISSUE TITLE
o1模型不支持system字段。

### ISSUE THREAD

**Issue by xf959211192** [MuiseDestiny/zotero-gpt#381]
### 这个问题是否已有issue

- [X] 我确认没有已有issue，且已阅读**常见问题**

### 运行环境

- **OS**: windows10
- **Zotero version**: 7
- **Plugin version**: 1.3.4

### 当前配置信息

api https://demo.voapi.top
secretKey sk-…DK1k
model o1-mini
temperature 0.5

### 问题详情

出错了，下面是一些报错信息：
HTTP POST https://demo.voapi.top/v1/chat/completions failed with status code 400:
{“error”:{“message”:“Unsupported value: ‘messages[0].role’ does not support ‘system’ with this model.  (request id: 20241015134541883761998k0IaVWWe) (request id: 202410151345581542705McxyN8pi) (request id: 20241015134557917467775dGtJYk7H) (request id: 20241015134557701750251SHISKyft)”,“type”:“invalid_request_error”,“param”:“messages[0].role”,“code”:“unsupported_value”}}

### 补充说明

稳定复现。网上相关解释资料 https://community.openai.com/t/o1-models-do-not-support-system-role-in-chat-completion/953880

**Comment by MuiseDestiny** [comment]
不支持o1模型。也不建议使用o1，在网页用用吧。
