### ISSUE TITLE
建议支持数学markdown语法

### ISSUE THREAD

**Issue by Meidong-Xia** [MuiseDestiny/zotero-gpt#42]
![image](https://user-images.githubusercontent.com/55342480/230336446-10926b14-99db-40ae-93e0-b4546225a107.png)
发现出来的markdown代码不能转换成相应的公式

**Comment by MuiseDestiny** [comment]
![image](https://user-images.githubusercontent.com/51939531/230727175-b03ffae4-9fc8-4036-9da7-45c520feb276.png)
