### ISSUE TITLE
如何将openai 的api 修改为其他的api？

### ISSUE THREAD

**Issue by mayq97** [MuiseDestiny/zotero-gpt#43]
大佬做的这个插件太好了。就是国内不太好用。
我可以在自己服务器上部署一个大模型。
请问如何将请求openai的api，改为请求我自己的api？

**Comment by MuiseDestiny** [comment]
下个版本提供接口

**Comment by MuiseDestiny** [comment]
/api 你的代理网站http开头的

回车即可

/model gpt-4

回车设置模型
