### ISSUE TITLE
版本即将下线通知

### ISSUE THREAD

**Issue by Qieminmin** [MuiseDestiny/zotero-gpt#46]
![屏幕截图 2023-04-09 215136](https://user-images.githubusercontent.com/115087718/230776682-499e906e-79c0-41f4-b885-af8575c83c53.png)
最新版本会弹出上图所示通知内容，然后就用不了了，关注公众号后也没有zotero插件的版本更新，

**Comment by MuiseDestiny** [comment]
> ![屏幕截图 2023-04-09 215136](https://user-images.githubusercontent.com/115087718/230776682-499e906e-79c0-41f4-b885-af8575c83c53.png) 最新版本会弹出上图所示通知内容，然后就用不了了，关注公众号后也没有zotero插件的版本更新，

免费的接口随时可能停用。可以试试申请密钥配置一下。

**Comment by xuanli1994** [comment]
请问配置自己的gpt的密匙，是需要注册gpt账号，在open ai官网去申请自己的密匙吗，另外，在使用中，会产生收费吗~

**Comment by MuiseDestiny** [comment]
> 请问配置自己的gpt的密匙，是需要注册gpt账号，在open ai官网去申请自己的密匙吗，另外，在使用中，会产生收费吗~

会，新注册会有免费额度。推荐自己注册。
