### ISSUE TITLE
摘要与所选文章不匹配

### ISSUE THREAD

**Issue by yeye42** [MuiseDestiny/zotero-gpt#5]
感谢大佬分享！我复制了示例中的摘要提问标签，但它提取的摘要与我所选文章不符

![image](https://user-images.githubusercontent.com/29211723/228293728-39732736-deb2-4916-8ca8-1401db3217ec.png)

**Comment by MuiseDestiny** [comment]
截图中的摘要应该是从pdf选取的摘要，这篇文章讲了啥会读取条目摘要

**Comment by yeye42** [comment]
谢谢！
