### ISSUE TITLE
流式传输GPT的响应结果

### ISSUE THREAD

**Issue by zfb132** [MuiseDestiny/zotero-gpt#6]
有时候GPT的返回内容会相对比较长，程序就只能等待直到整个结果接收完毕才可以显示  
建议采用流式传输，这样基本可以做到提交问题就立马开始实时传输答案，体验效果与网页版类似  

我自己Fork代码并添加了[这个功能](https://github.com/zfb132/zotero-gpt/commits/bootstrap) ，如果需要的话我可以提PR

测试插件
[zotero-gpt-0.0.0.zip](https://github.com/MuiseDestiny/zotero-gpt/files/11094067/zotero-gpt-0.0.0.zip)

**Comment by MuiseDestiny** [comment]
已经流了，没发布

**Comment by MuiseDestiny** [comment]
确实，流起来速度相当快。感谢你的贡献！我会查看你的代码继续优化流的形式！

**Comment by zfb132** [comment]
好的  
你开发的这几款插件，都很实用
