### ISSUE TITLE
设置api

### ISSUE THREAD

**Issue by skyerGalaxy** [MuiseDestiny/zotero-gpt#64]
![image](https://user-images.githubusercontent.com/90626136/231708378-a09f6963-d6b4-40fc-b2e9-9ecc00ae0deb.png)

![image](https://user-images.githubusercontent.com/90626136/231708138-286492ae-d6b8-4a7b-a372-3ec0b512843a.png)
- api是什么呀,我在另一个软件了设置的api是`https://api.openai.com`完全可以使用,这里就提示无效,怎么解决?
- 模型设置 可以不设置吗?

**Comment by skyerGalaxy** [comment]
我输入`http://api.openai.com`,它让我输入`https`

**Comment by MuiseDestiny** [comment]
> 我输入`http://api.openai.com`,它让我输入`https`

注意，api一般以v1结尾

**Comment by MuiseDestiny** [comment]
比如https://api.openai.com/v1

**Comment by skyerGalaxy** [comment]
> 比如https://api.openai.com/v1

谢谢!
