### ISSUE TITLE
AskPDF出现报错

### ISSUE THREAD

**Issue by wangleping2000** [MuiseDestiny/zotero-gpt#65]
You exceeded your current quota, please check your plan and billing details
![image](https://user-images.githubusercontent.com/87556341/231772020-1c741657-c1d5-4935-95ee-966c8f686820.png)

**Comment by MuiseDestiny** [comment]
> You exceeded your current quota, please check your plan and billing details ![image](https://user-images.githubusercontent.com/87556341/231772020-1c741657-c1d5-4935-95ee-966c8f686820.png)

配额不足，你的号有问题。到期了或者用了不匹配的模型

**Comment by wangleping2000** [comment]
![image](https://user-images.githubusercontent.com/87556341/231773985-5f7ffb9e-8318-43da-90ba-e9abba170240.png)
这种是不是都是默认类型的啊，gpt-3.5-turbo，我只是申请了账号，GPT也正常用

**Comment by MuiseDestiny** [comment]
填写secretKey了吗

**Comment by fanqiangniubi** [comment]
![image](https://user-images.githubusercontent.com/87556341/231776274-13656ad9-0f1b-48f8-bb79-224905b4b786.png)
![image](https://user-images.githubusercontent.com/87556341/231776468-72d2fce8-c6d1-46cd-a43e-3e788528bb0d.png)

目前是这样

**Comment by MuiseDestiny** [comment]
重新发吧，密钥暴露了。密钥要打马

**Comment by wangleping2000** [comment]
![image](https://user-images.githubusercontent.com/87556341/231777368-ed0c3196-42ea-40fd-92e8-8a5614c649c2.png)

![image](https://user-images.githubusercontent.com/87556341/231777016-e3615adf-2555-4245-89a4-5b5a2520afc7.png)

**Comment by wangleping2000** [comment]
pip install llama-index的时候出了问题
![image](https://user-images.githubusercontent.com/87556341/231778070-e3a5f609-c5f0-4212-9c48-50a0f7bf78aa.png)

**Comment by MuiseDestiny** [comment]
注意，那个网页是不消耗配额的

**Comment by MuiseDestiny** [comment]
你要去看你剩下的额度，具体怎么看网上搜一下

**Comment by MuiseDestiny** [comment]
网页永久免费，只要有帐号，但跟你的apikey有没有权限是两码事

**Comment by wangleping2000** [comment]
![image](https://user-images.githubusercontent.com/87556341/231781301-a7187b19-4d7d-4d9b-854b-48eb2d1e5756.png)
这个是不是说我得重新买

**Comment by MuiseDestiny** [comment]
> ![image](https://user-images.githubusercontent.com/87556341/231781301-a7187b19-4d7d-4d9b-854b-48eb2d1e5756.png) 这个是不是说我得重新买

Yes,你也可以考虑重新注册一个有5美金额度，更划算

**Comment by Flying7514** [comment]
api_key是要花钱的
