### ISSUE TITLE
这个是需要科学上网才能国内正常使用吗？

### ISSUE THREAD

**Issue by likenihood** [MuiseDestiny/zotero-gpt#69]
修改了secrekey后没啥反应，我在OPENAI官网可以正常使用（某些原因我只想让浏览器翻墙）

**Comment by Zmalmal1** [comment]
你在哪里输入的密钥啊?朋友! 我在输入密钥的这一步就卡住了

**Comment by MuiseDestiny** [comment]
> 修改了secrekey后没啥反应，我在OPENAI官网可以正常使用（某些原因我只想让浏览器翻墙）

官网能使用，说明你有openai的号。不代表有token

**Comment by hanqing0521** [comment]
一样的，我现在的sk是可用的，全局代理的话能够正常工作，实际上默认的sk在代理下也可以用。希望能有一个socks或者http的代理设置。同样不是很想全局代理……
