### ISSUE TITLE
求问大佬这个是怎么回事啊，密匙已经配上了，模型也设置了，不知道为啥这样

### ISSUE THREAD

**Issue by Hr2306000** [MuiseDestiny/zotero-gpt#73]
![1681479368748](https://user-images.githubusercontent.com/130767960/232059262-c90efe33-fa6f-4a67-87a8-2fbf966ee67d.png)

**Comment by MuiseDestiny** [comment]
模型二选一，不是这么设置的

**Comment by Hr2306000** [comment]
！！可以了谢谢谢谢！gpt-4模型我好像不可以，3.5可以，谢谢大佬

**Comment by zfb132** [comment]
`GPT-4`模型目前处于内测阶段，需要填写申请 [gpt-4-api](https://openai.com/waitlist/gpt-4-api) ，并收到审核通过的邮件才可以使用
