### ISSUE TITLE
输入的文本超出模型最大tokens

### ISSUE THREAD

**Issue by Qieminmin** [MuiseDestiny/zotero-gpt#75]
求问作者大佬，出现这个问题是什么原因呢，我用的是自己的api
![image](https://user-images.githubusercontent.com/115087718/232106743-f8c40bbe-0ebc-4881-88d0-fbfdd982646b.png)

**Comment by baicaifanbao** [comment]
我找到了这个，但是我不懂编程😂https://github.com/zhayujie/chatgpt-on-wechat/issues/343

**Comment by Qieminmin** [comment]
+1，同是编程小白😂

**Comment by zfb132** [comment]
在会话里聊的次数多了，历史记录太长导致的

**Comment by Qieminmin** [comment]
好的好的，谢谢啦
