### ISSUE TITLE
或许可以考虑增加一个tag“将内容导入到笔记中”

### ISSUE THREAD

**Issue by dreistein543** [MuiseDestiny/zotero-gpt#78]
在阅读文献做笔记时，往往具有相同的流程：
- 文章的主要内容
- 文章的研究方法
- 文章研究的创新点

那么，是否可以添加一个tag，把gpt生成的内容自动导入到笔记中（类似Zotero自带的“通过注释来添加笔记”功能）
特别是，当结合 searchitem 快速筛选数篇相关文献，希望快速整理出上述内容再精读的话，增加这一tag无疑更加方便。

P.S. 作者也可以考虑将这一功能集成到[better note 插件](https://github.com/MuiseDestiny/zotero-better-notes)中，这样也更聚焦？

**Comment by MuiseDestiny** [comment]
正在与better notes集成

**Comment by MuiseDestiny** [comment]
gpt不会做到其他插件里，但他可以与任何插件联动

**Comment by dreistein543** [comment]
> 正在与better notes集成

期待😚



> gpt不会做到其他插件里，但他可以与任何插件联动

我也是有这种感觉，gpt不适合做到其他插件里，我的意思仅仅是通过better note里增加功能来调用gpt生成的内容
