### ISSUE TITLE
GPT 4 与 GPT 3.5 速度对比测试

### ISSUE THREAD

**Issue by zfb132** [MuiseDestiny/zotero-gpt#9]
#8 
速度与文本质量仅为本人网络环境下的一次测试，供参考  
**GPT 3.5**：
![gpt3 5](https://user-images.githubusercontent.com/18099238/228423507-ce99c5b3-6dae-45a2-9c05-e6e35f6c5873.gif)
**GPT 4**：
![gpt4](https://user-images.githubusercontent.com/18099238/228423591-f6976914-ef4d-4313-ac84-a7705f69245d.gif)

**Comment by EdwardGiao** [comment]
兄弟能指导下密钥是什么吗？

**Comment by MuiseDestiny** [comment]
感谢，有了直观上的了解

**Comment by zfb132** [comment]
> 兄弟能指导下密钥是什么吗？

前提是你在[这里](https://openai.com/waitlist/gpt-4-api)提交申请，且获得权限（收到一封邮件`You're invited to use the OpenAI GPT-4 API!`）

**Comment by EdwardGiao** [comment]
谢谢！刚才在[OpenAI官网](https://platform.openai.com)申请了一个API Key，跟您发的这个Chap-4的是不一样吗？

**Comment by zfb132** [comment]
> 感谢，有了直观上的了解

@MuiseDestiny 不过我用chatgpt web之类的仓库搭建网页测试gpt 4的速度，发现速度还是很快的，差距并没有截图那么大，具体原因还有待分析

**Comment by zfb132** [comment]
> 谢谢！刚才在[OpenAI官网](https://platform.openai.com)申请了一个API Key，跟您发的这个Chap-4的是不一样吗？

目前，官网申请的key只能用gpt 3.5  
只有按照我上面那条加入waitlist，通过之后，你之前申请的那个key（以及新创建的key）才能访问gpt 4的模型

**Comment by EdwardGiao** [comment]
懂了，感谢！
