### ISSUE TITLE
我使用的API2D，配置如下，请问在askPDF的时候，出现 status code 439错误是什么原因

### ISSUE THREAD

**Issue by YueXiaoqian** [MuiseDestiny/zotero-gpt#90]
我使用的API2D，配置如下，请问在askPDF的时候，出现status code 439错误是什么原因

<img width="258" alt="image" src="https://user-images.githubusercontent.com/53172337/232291129-298afdda-853c-45cf-a710-0bc0993e106e.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/53172337/232291136-81abd2b0-a6c3-4693-aa91-5953f6d5ef24.png">
<img width="156" alt="image" src="https://user-images.githubusercontent.com/53172337/232291140-ed0cabb5-693a-4218-a5b5-7e0b560a37fe.png">

**Comment by YueXiaoqian** [comment]
正常对话是可以用的，askpdf时报错

**Comment by YueXiaoqian** [comment]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/53172337/232291403-a1dd4413-83db-42d3-9163-161be77e0f50.png">

**Comment by MuiseDestiny** [comment]
看下还有余额嘛

**Comment by MuiseDestiny** [comment]
我试了下确实不行，有可能代理那边有点问题。明天再试试

**Comment by YueXiaoqian** [comment]
还有余额的，好的 明天再试试，谢谢啦

**Comment by YueXiaoqian** [comment]
现在可以了 感谢
